# Tutorial#1

In [2]:
import pandas as pd

df = pd.read_csv('data/survey_results_public.csv')
sdf = pd.read_csv('data/survey_results_schema.csv')

In [8]:
pd.set_option('display.max_columns', 79)
pd.set_option('display.max_rows',180)

In [3]:
df.shape

(73268, 79)

In [4]:
sdf.head(3)

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB

In [5]:
sdf.tail(3)

,qid,qname,question,force_resp,type,selector
76,QID294,TrueFalse_1,Are you involved in supporting new hires durin...,NaN,MC,MAVR
77,QID294,TrueFalse_2,Do you use learning resources provided by your...,NaN,MC,MAVR
78,QID294,TrueFalse_3,Does your employer give you time to learn new ...,NaN,MC,MAVR

# Tutorial#2

In [6]:
peeps = {
    'a' : [1,2,3],
    'b' : [4,5,6]
}

dp = pd.DataFrame(peeps)

In [7]:
dp['a'] # is a Series object (which is mainly just a one-dimensional array)

0    1
1    2
2    3
Name: a, dtype: int64

In [8]:
dp.columns

Index(['a', 'b'], dtype='object')

In [9]:
dp[['a','b']]   # returns another data frame

   a  b
0  1  4
1  2  5
2  3  6

In [10]:
dp.iloc[0]  # returns rows (iloc = searches by index location)

a    1
b    4
Name: 0, dtype: int64

In [11]:
dp.iloc[[0,1]]

   a  b
0  1  4
1  2  5

In [12]:
dp.iloc[0,1]    #(row,column)

4

In [13]:
dp.iloc[[0,1],1]    #for 2 rows

0    4
1    5
Name: b, dtype: int64

In [14]:
dp.loc[[0,1,2],'a'] #loc works same for rows but for columns, specify there column name

0    1
1    2
2    3
Name: a, dtype: int64

### Using stack Overflows data

In [15]:
df['Country'].value_counts()

Country
United States of America                                13543
India                                                    6639
Germany                                                  5395
United Kingdom of Great Britain and Northern Ireland     4190
Canada                                                   2490
France                                                   2328
Brazil                                                   2109
Poland                                                   1732
Netherlands                                              1555
Spain                                                    1521
Italy                                                    1514
Australia                                                1462
Russian Federation                                       1229
Turkey                                                   1020
Sweden                                                   1020
Switzerland                                               932
Austria                                                   833
Israel                                                    795
Iran, Islamic Republic of...                              723
Pakistan                                                  711
Czech Republic                                            692
China                                                     632
Belgium                                                   626
Bangladesh                                                613
Ukraine                                                   593
Romania                                                   581
Mexico                                                    574
Portugal                                                  563
Greece                                                    548
Denmark                                                   547
Indonesia                                                 537
Argentina                                                 521
Nigeria                                                   517
South Africa                                              493
Norway                                                    479
Finland                                                   468
Hungary                                                   466
New Zealand                                               440
Egypt                                                     400
Philippines                                               366
Bulgaria                                                  364
Colombia                                                  341
Japan                                                     333
Ireland                                                   332
Viet Nam                                                  317
Sri Lanka                                                 296
Slovenia                                                  286
Serbia                                                    282
Kenya                                                     270
Taiwan                                                    233
South Korea                                               229
Slovakia                                                  229
Morocco                                                   226
Singapore                                                 226
Nepal                                                     222
Lithuania                                                 212
Malaysia                                                  206
Chile                                                     203
Croatia                                                   192
Hong Kong (S.A.R.)                                        184
Thailand                                                  175
United Arab Emirates                                      165
Estonia                                                   141
Peru                                                      136
Belarus                                                   136
Venezuela, Bolivarian Republic of...                      119
Saudi Arabia                                              116
Uruguay                                                   106
Georgia                                                   105
Bosnia and Herzegovina                                    103
Tunisia                                                   101
Latvia                                                     95
Armenia                                                    93
Ghana                                                      86
Uzbekistan                                                 84
Dominican Republic                                         83
Ecuador                                                    83
Costa Rica                                                 76
Ethiopia                                                   75
Republic of Korea                                          72
Lebanon                                                    71
Kazakhstan                                                 70
Azerbaijan                                                 69
Afghanistan                                                69
Jordan                                                     64
Uganda                                                     63
Cyprus                                                     61
Albania                                                    59
Luxembourg                                                 56
Guatemala                                                  54
Iraq                                                       54
Myanmar                                                    53
The former Yugoslav Republic of Macedonia                  51
El Salvador                                                45
Bolivia                                                    44
Paraguay                                                   42
Malta                                                      39
Nomadic                                                    37
Republic of Moldova                                        37
Algeria                                                    36
Syrian Arab Republic                                       35
Cambodia                                                   35
Cameroon                                                   34
Palestine                                                  34
Sudan                                                      32
Cuba                                                       31
Zimbabwe                                                   30
Kosovo                                                     29
Honduras                                                   28
Panama                                                     28
United Republic of Tanzania                                28
Iceland                                                    28
Madagascar                                                 26
Jamaica                                                    22
Kyrgyzstan                                                 22
Mauritius                                                  21
Qatar                                                      20
Zambia                                                     20
Rwanda                                                     20
Kuwait                                                     20
Montenegro                                                 19
Mongolia                                                   19
Nicaragua                                                  18
Turkmenistan                                               16
Andorra                                                    15
Côte d'Ivoire                                              14
Malawi                                                     14
Bahrain                                                    14
Yemen                                                      14
Oman                                                       13
Trinidad and Tobago                                        13
Libyan Arab Jamahiriya                                     13
Senegal                                                    13
Angola                                                     12
Congo, Republic of the...                                  12
Somalia                                                    12
Isle of Man                                                12
Maldives                                                   12
Tajikistan                                                 11
Benin                                                      11
Mozambique                                                 11
Mali                                                       10
Togo                                                        9
Swaziland                                                   7
Democratic Republic of the Congo                            7
Lao People's Democratic Republic                            7
Barbados                                                    6
Guyana                                                      6
Botswana                                                    6
Guinea                                                      5
Namibia                                                     5
Bhutan                                                      5
Suriname                                                    4
North Korea                                                 4
Timor-Leste                                                 4
Cape Verde                                                  4
Bahamas                                                     4
Niger                                                       3
Belize                                                      3
Saint Lucia                                                 3
Chad                                                        3
Haiti                                                       3
Gambia                                                      2
Mauritania                                                  2
Liberia                                                     2
Gabon                                                       2
Palau                                                       2
Papua New Guinea                                            2
Antigua and Barbuda                                         2
Lesotho                                                     2
Fiji                                                        2
Sierra Leone                                                2
San Marino                                                  1
Burkina Faso                                                1
Brunei Darussalam                                           1
Monaco                                                      1
Djibouti                                                    1
Seychelles                                                  1
Solomon Islands                                             1
Saint Kitts and Nevis                                       1
Name: count, dtype: int64

In [16]:
df.loc[2]

ResponseId                                                                        3
MainBranch                        I am not primarily a developer, but I write co...
Employment                                                      Employed, full-time
RemoteWork                                     Hybrid (some remote, some in-person)
CodingActivities                                                              Hobby
EdLevel                             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
LearnCode                         Books / Physical media;Friend or family member...
LearnCodeOnline                   Technical documentation;Blogs;Programming Game...
LearnCodeCoursesCert                                                            NaN
YearsCode                                                                        14
YearsCodePro                                                                      5
DevType                           Data scientist or machine learning specialist;...
OrgSize                                                          20 to 99 employees
PurchaseInfluence                                             I have some influence
BuyNewTool                                                                      NaN
Country                           United Kingdom of Great Britain and Northern I...
Currency                                                        GBP\tPound sterling
CompTotal                                                                   32000.0
CompFreq                                                                     Yearly
LanguageHaveWorkedWith                            C#;C++;HTML/CSS;JavaScript;Python
LanguageWantToWorkWith                        C#;C++;HTML/CSS;JavaScript;TypeScript
DatabaseHaveWorkedWith                                         Microsoft SQL Server
DatabaseWantToWorkWith                                         Microsoft SQL Server
PlatformHaveWorkedWith                                                          NaN
PlatformWantToWorkWith                                                          NaN
WebframeHaveWorkedWith                                                   Angular.js
WebframeWantToWorkWith                                           Angular;Angular.js
MiscTechHaveWorkedWith                                                       Pandas
MiscTechWantToWorkWith                                                         .NET
ToolsTechHaveWorkedWith                                                         NaN
ToolsTechWantToWorkWith                                                         NaN
NEWCollabToolsHaveWorkedWith                                Notepad++;Visual Studio
NEWCollabToolsWantToWorkWith                                Notepad++;Visual Studio
OpSysProfessional use                                                       Windows
OpSysPersonal use                                                           Windows
VersionControlSystem                                                            Git
VCInteraction                                                           Code editor
VCHostingPersonal use                                                           NaN
VCHostingProfessional use                                                       NaN
OfficeStackAsyncHaveWorkedWith                                                  NaN
OfficeStackAsyncWantToWorkWith                                                  NaN
OfficeStackSyncHaveWorkedWith                                       Microsoft Teams
OfficeStackSyncWantToWorkWith                                       Microsoft Teams
Blockchain                                                         Very unfavorable
NEWSOSites                        Collectives on Stack Overflow;Stack Overflow;S...
SOVisitFreq                                                  Multiple times per day
SOAccount                                                                       Yes
SOPartFreq                                                   Multiple times per day
SOComm                                                                      Neutral
Age                                                                 25-34 years old
Gender                                                                          Man
Trans                                                                            No
Sexuality                                                                  Bisexual
Ethnicity                                                                     White
Accessibility                                                     None of the above
MentalHealth                      I have a mood or emotional disorder (e.g., dep...
TBranch                                                                          No
ICorPM                                                                          NaN
WorkExp                                                                         NaN
Knowledge_1                                                                     NaN
Knowledge_2                                                                     NaN
Knowledge_3                                                                     NaN
Knowledge_4                                                                     NaN
Knowledge_5                                                                     NaN
Knowledge_6                                                                     NaN
Knowledge_7                                                                     NaN
Frequency_1                                                                     NaN
Frequency_2                                                                     NaN
Frequency_3                                                                     NaN
TimeSearching                                                                   NaN
TimeAnswering                                                                   NaN
Onboarding                                                                      NaN
ProfessionalTech                                                                NaN
TrueFalse_1                                                                     NaN
TrueFalse_2                                                                     NaN
TrueFalse_3                                                                     NaN
SurveyLength                                                  Appropriate in length
SurveyEase                                               Neither easy nor difficult
ConvertedCompYearly                                                         40205.0
Name: 2, dtype: object

In [17]:
df.loc[55,'Country']

'United States of America'

#### Slicing (It is inclusive for start and end both)

In [18]:
df.loc[0:4,'Country']   #same as df.loc[[0,1,2,3,4], 'Country']

0                                                  NaN
1                                               Canada
2    United Kingdom of Great Britain and Northern I...
3                                               Israel
4                             United States of America
Name: Country, dtype: object

In [19]:
df.loc[20:30,'Employment':'DevType']  #column slicing DAMN!

,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType
20,"Student, part-time;Employed, part-time","Hybrid (some remote, some in-person)",Hobby,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;V...,NaN,1,NaN,Student
21,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Other (please specify):,NaN,NaN,5,4,"Developer, full-stack"
22,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,Something else,Books / Physical media,NaN,NaN,25,20,"Developer, back-end"
23,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Written Tutorials;Stack Overflow;Written...,NaN,10,6,Other (please specify):
24,"Independent contractor, freelancer, or self-em...",Fully remote,I don’t code outside of work,Some college/university study without earning ...,NaN,NaN,NaN,40,40,"Developer, full-stack"
25,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Codecademy;edX;Udacity,16,9,"Developer, back-end;Developer, mobile"
26,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,NaN,10,5,"Developer, full-stack;Developer, back-end"
27,"Not employed, and not looking for work",NaN,NaN,Something else,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,NaN,4,NaN,NaN
28,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,14,"Developer, desktop or enterprise applications;..."
29,"Employed, full-time;Independent contractor, fr...",Fully remote,Hobby;Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow,NaN,27,22,"Developer, full-stack"
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Tutorial#3

In [20]:
peeps2 = {
    'first':['awais','talha','saleh'],
    'last':['ahmad','mumtaz','jahanzaib'],
    'email':['awais123','talha123','saleh123']
}

dp2 = pd.DataFrame(peeps2)

In [21]:
dp2.set_index('email')  #sets index as email(chose this as email is unique)

          first       last
email
awais123  awais      ahmad
talha123  talha     mumtaz
saleh123  saleh  jahanzaib

In [22]:
dp2.set_index('email',inplace=True) #permanently sets email as index

In [23]:
dp2

          first       last
email
awais123  awais      ahmad
talha123  talha     mumtaz
saleh123  saleh  jahanzaib

In [24]:
dp2.reset_index(inplace=True)
dp2

      email  first       last
0  awais123  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

### Stack Overflow Exapmle

In [25]:
df.set_index('ResponseId',inplace=True) #can also do this from pd.read_csv(...,index_col='')
df.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [26]:
sdf.set_index('qname',inplace=True)
sdf.head()

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,False,MC,MAVR

In [27]:
sdf.loc['Employment','question']

'Which of the following best describes your current employment status?'

In [28]:
sdf.sort_index()

,qid,question,force_resp,type,selector
qname,,,,,
Accessibility,QID124,"Which of the following describe you, if any? P...",False,MC,MAVR
Age,QID127,What is your age?,False,MC,MAVR
Blockchain,QID305,"How favorable are you about blockchain, crypto...",False,MC,SAVR
BuyNewTool,QID279,"When buying a new tool or software, how do you...",False,MC,MAVR
CodingActivities,QID297,Which of the following best describes the code...,False,MC,MAVR
CompFreq,QID52,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
CompTotal,QID51,What is your current total compensation (salar...,False,TE,SL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,DL
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
DevType,QID31,Which of the following describes your current ...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,False,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,False,MC,MAVR
Ethnicity,QID126,"Which of the following describe you, if any? P...",False,MC,MAVR
Frequency,QID290,How frequently do you experience each of the f...,False,Matrix,Likert
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
Gender,QID122,"Which of the following describe you, if any? P...",False,MC,MAVR
ICorPM,QID287,Are you an independent contributor or people m...,False,MC,SAVR
Knowledge,QID289,Please rate your level of agreement with the f...,False,Matrix,Likert
Knowledge_1,QID289,I have interactions with people outside of my ...,NaN,MC,MAVR
Knowledge_2,QID289,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
Knowledge_3,QID289,I can find up-to-date information within my or...,NaN,MC,MAVR
Knowledge_4,QID289,I am able to quickly find answers to my questi...,NaN,MC,MAVR
Knowledge_5,QID289,I know which system or resource to use to find...,NaN,MC,MAVR
Knowledge_6,QID289,I often find myself answering questions that I...,NaN,MC,MAVR
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
LearnCode,QID276,How did you learn to code? Select all that apply.,False,MC,MAVR
LearnCodeCoursesCert,QID306,What online courses or certifications do you u...,False,MC,MAVR
LearnCodeOnline,QID281,What online resources do you use to learn to c...,False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
MentalHealth,QID125,"Which of the following describe you, if any? P...",False,MC,MAVR
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,False,MC,MAVR
OfficeStackAsync,QID282,Which <b>collaborative work management tools</...,False,Matrix,Likert
OfficeStackSync,QID307,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
Onboarding,QID293,The time it takes to onboard new hires at my c...,False,MC,SAVR
OpSys,QID71,What is the primary <b>operating system</b> in...,False,Matrix,Likert
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,MAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
ProfessionalTech,QID304,My company has:,False,MC,MAVR
PurchaseInfluence,QID278,"What level of influence do you, personally, ha...",False,MC,SAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S2,QID190,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S3,QID61,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S4,QID91,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S5,QID121,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S6,QID295,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
S7,QID131,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,MAVR
SOTeamsUsage,QID286,Does your team use Stack Overflow for Teams?,False,MC,SAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,MAVR
Sexuality,QID136,"Which of the following describe you, if any? P...",False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
TBranch,QID299,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
TimeAnswering,QID292,"On an average day, how much time do you typica...",False,MC,SAVR
TimeSearching,QID291,"On an average day, how much time do you typica...",False,MC,SAVR
ToolsTech,QID275,Which <b>developer </b><strong>tools</strong> ...,False,Matrix,Likert
Trans,QID153,Do you identify as transgender?,False,MC,MAVR
TrueFalse,QID294,Last few questions...,False,Matrix,Likert
TrueFalse_1,QID294,Are you involved in supporting new hires durin...,NaN,MC,MAVR
TrueFalse_2,QID294,Do you use learning resources provided by your...,NaN,MC,MAVR
TrueFalse_3,QID294,Does your employer give you time to learn new ...,NaN,MC,MAVR
VCHosting,QID285,What version control hosting service are you u...,False,Matrix,Likert
VCInteraction,QID284,How do you interact with your version control ...,False,MC,MAVR
VersionControlSystem,QID283,What are the primary <b>version control system...,False,MC,MAVR
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

# Tutorial#4

In [29]:
filt = (dp2['last'] == 'ahmad') | (dp2['first'] == 'talha')   # and = & .... or = |
dp2[filt]

      email  first    last
0  awais123  awais   ahmad
1  talha123  talha  mumtaz

In [30]:
# Also this
dp2.loc[filt,'email']

0    awais123
1    talha123
Name: email, dtype: object

In [31]:
dp2.loc[~filt,'email']

2    saleh123
Name: email, dtype: object

In [32]:
sal = df['DevType'].str.contains('machine learning', na=False)
df.loc[sal]

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
42,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,3,3,Data scientist or machine learning specialist;...,20 to 99 employees,I have little or no influence,Visit developer communities like Stack Overflo...,Israel,ILS\tIsraeli new shekel,19000.0,Monthly,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;Python;SQL,PostgreSQL,PostgreSQL;Redis,AWS;Google Cloud,AWS,NaN,NaN,Keras;NumPy;Pandas;Scikit-learn;TensorFlow,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Hug...,Docker,Docker,IPython/Jupyter;Vim,IPython/Jupyter;PyCharm;Vim,Linux-based,Windows,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Slack,Slack,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,"No, not really",18-24 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,I have an anxiety disorder,Yes,Independent contributor,3.0,Agree,Neither agree nor disagree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,10+ times a week,Never,30-60 minutes a day,15-30 minutes a day,Somewhat short,NaN,NaN,Yes,Yes,Appropriate in length,Neither easy nor difficult,68160.0
51,"I am not primarily a developer, but I write co...","Employed, full-time;Student, full-time",Full in-person,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Written Tutorial...,NaN,11,NaN,Data scientist or machine learning specialist;...,NaN,NaN,NaN,Czech Republic,NaN,NaN,NaN,Bash/Shell;Julia;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Scikit-learn;Torch/PyTorch,NaN,NaN,NaN,Neovim,NaN,Linux-based,Linux-based,Git,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams;Slack,NaN,Unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,"No, not at all",25-34 years old,Man,No,Straight / Heterosexual,White;European,None of the above,None of the above,Yes,NaN,4.0,Strongly disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15-30 minutes a day,Less than 15 minutes a day,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
62,I code primarily as a hobby,"Student, part-time;Independent contractor, fre...",Fully remote,Hobby;Freelance/contract work,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Coursera,2,NaN,Data scientist or machine learning specialist;...,NaN,NaN,Visit developer communities like Stack Overflow,Mexico,NaN,NaN,NaN,Bash/Shell;HTML/CSS;Python,Assembly;Dart;Rust;Solidity;SQL,PostgreSQL,Redis;SQLite,Heroku,AWS;Firebase;Google Cloud;Linode;OpenStack,Flask,NaN,NumPy;Pandas;Scikit-learn,Flutter,Docker;Puppet,Yarn,Vim;Visual Studio Code,NaN,Linux-based,Linux-based,Git,Command-line,NaN,NaN,NaN,NaN,Cisco Webex Teams;Zoom,Zoom,Favorable,I have never visited Stack Overflow or the Sta...,NaN,Yes,Less than once per month or monthly,Neutral,25-34 years old,Man,No,Straight / Heterosexual,Central American,NaN,I have a concentration and/or memory disorder ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
86,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,10,7,Data scientist or machine learning specialist;...,100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,United States of America,USD\tUnited States dollar,95000.0,Yearly,Bash/Shell;Java;Python;SQL,Clojure;Dart;Go;Java;JavaScript;Kotlin;Python;...,MariaDB;MySQL,MariaDB;MySQL,NaN,NaN,NaN,NaN,Keras;NumPy;Scikit-learn;TensorFlow;Torch/PyTo...,Flutter;Keras;NumPy;Scikit-learn;Spring;Tensor...,NaN,NaN,Eclipse;Notepad++;PyCharm,Eclipse;IntelliJ;Notepad++;PyCharm,Linux-based;Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,Microsoft Teams;Slack;Zoom,Indifferent,Stack Overflow,Daily or almost daily,No,NaN,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,Prefer not to say,Yes,Independent contributor,7.0,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,6-10 times a week,1-2 times a week,60-120 minutes a day,15-30 minutes a day,Somewhat short,Developer portal or other central places to fi...,No,No,Yes,Appropriate in length,Easy,95000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73197,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",School or academic work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Friend or family member;Other online resources...,Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Codecademy,10,Less than 1 year,Data scientist or machine learning specialist;...,100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,Netherlands,EUR European Euro,2900.0,Monthly,Bash/Shell;PowerShell;Python;SQL,Bash/Shell;Python;Rust;SQL,MySQL,MySQL,Microsoft Azure;VMware,Microsoft Azure;VMware,NaN,NaN,Apache Spark;Hadoop;NumPy;Pandas;Scikit-learn;...,Apache Spark;Hadoop;NumPy;Pandas;Scikit-learn;...,NaN,NaN,IntelliJ;IPython/Jupyter;PyCharm;Vim;Visual St...,IntelliJ;IPython/Jupyter;PyCharm;Vim;Visual St...,Windows;Windows Subsystem for Linux (WSL),Linux-based;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Microsoft Planner,Mattermost;Microsoft Teams;Slack;Zoom,Microsoft Teams;Zoom,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,Neutral,25-34 years old,Man,No,Bisexual,European;North American,None of the above,None of the above,Yes,Independent contributor,NaN,Agree,Disagree,Disagree,Neither agree nor disagree,Neither agree nor disagree,Disagree,Disagree,1-2 times a week,3-5 times a week,1-2 times a week,Over 120 minutes a day,15-30 minutes a day,Somewhat long,Developer portal or other central places to fi...,No,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
73230,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,NaN,18,15,Data scientist or machine learning specialist;...,500 to 999 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,325000.0,Yearly,Bash/Shell;C++;PowerShell;Python;SQL,C++;Python,Microsoft SQL Server;MySQL,CouchDB;Microsoft SQL Server;MySQL;Redis,NaN,NaN,NaN,NaN,NumPy;Pandas,NumPy;Pandas;Scikit-learn,NaN,NaN,IPython/Jupyter;Notepad++;Vim;Visual Studio Code,IPython/Jupyter;Vim;Visual Studio Code,Windows,Linux-based,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Cisco Webex Teams,Slack,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,45-54 years old,Man,No,Straight / Heterosexual,Prefer not to say,None of the above,None of the above,Yes,People manager,15.0,Strongly agree,Agree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Never,6-10 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Somewhat long,None of these,Yes,No,No,Appropriate in length,Easy,NaN
73235,I am a developer by profession,"Employed, full-time",Full in-person,Bootstrapping a business,NaN,Books / Physical media;Online Courses or Certi...,NaN,Coursera;Udemy;edX;Skillsoft,3,4,Data scientist or machine learning specialist;...,10 to 19 employees,I have some influence,Ask developers I know/work with,Thailand,THB\tThai baht,NaN,Weekly,Assembly;Bash/Shell;JavaScript;PHP;Python;R;SA...,APL;C;C#;C++,Cassandra;CouchDB;MongoDB;MySQL;SQLite,NaN,Firebase;Google Cloud,AWS;Colocation,Angular.js;Django;Flask;jQuery;Node.js;React.j...,NaN,Apache Kafka;Flutter;Hadoop;Keras;NumPy;Pandas...,NaN,npm,Unity 3D,Android Studio;Atom;IPython/Jupyter;PyCharm;Vi...,NaN,NaN,macOS,Git,Command-line;Version control hosting service w...,NaN,NaN,NaN,NaN,Microsoft Teams;Slack;Zoom,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Less than once per month or monthly,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Man,Yes,Queer,Asian,NaN,Prefer not to say,Yes,People manager,20.0,Agree,Agree,Disagree,Strongly disagree,Agree,Neither agree nor disagree,Strongly disagree,1-2 times a week,1-2 times a week,3-5 times a week,15-30 minutes a day,15-30 minutes a day,Very short,DevOps function,Yes,NaN,NaN,Too short,Neither easy nor difficult,NaN
73255,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Codecademy;edX,7,6,Data scientist or machine learning specialist;...,"10,000 or more employees",I have some influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,115000.0,Yearly,R,Python;R,NaN,NaN,AWS,NaN,NaN,NaN,Tidyverse,Keras;NumPy;Pandas;Scikit-learn;Tidyverse;Tens...,NaN,NaN,RStudio,IPython/Jupyter;RStudio,Windows,Windows,Git,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Favorable,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,16.0,Strongly agree,Strongly agree,Disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,6-10 times a week,6-10 times a week,60-120 minutes a day,30-60 minutes a day,Somewhat long,Developer portal or other central places to fi...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,Data scientist or machine learning specialist,I don’t know,I have little or no influence,Other (please specify):;Ask developers I know/...,United States of America,USD\tUnited States dollar,107000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;Python,Elasticsearch;MongoDB;Oracle;SQLite,Elasticsearch;Neo4j;SQLite,NaN,NaN,FastAPI;Flask;React.js,FastAPI;React.js,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Tor...,NumPy;Pandas;Torch/PyTorch;Hugging Face Transf...,NaN,NaN,IPython/Jupyter;Notepad++;Spyder;Vim;Visual St...,Notepad++;Spyder;Vim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Rocketchat,NaN,Unsure,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,10+ times a week,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN

In [33]:
sdf.loc['Knowledge_1']

qid                                                      QID289
question      I have interactions with people outside of my ...
force_resp                                                  NaN
type                                                         MC
selector                                                   MAVR
Name: Knowledge_1, dtype: object

# Tutorial#5

In [34]:
dp2.columns

Index(['email', 'first', 'last'], dtype='object')

In [35]:
dp2.columns = ['a','b','c']
dp2

          a      b          c
0  awais123  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [36]:
dp2.columns = ['first', 'last', 'email']
dp2

      first   last      email
0  awais123  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [37]:
dp2.rename(columns={                     #changes specified column names
    'first_name':'first',
    'last_name':'last'}, inplace=True)
dp2

      first   last      email
0  awais123  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [38]:
dp2.loc[0,'first'] = 'sohaib'
dp2

      first   last      email
0    sohaib  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [39]:
filt = (dp2['last'] == 'ahmad')
dp2.loc[filt,'first'] = 'awais'
dp2

      first   last      email
0    sohaib  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [40]:
dp2['email'] = dp2['email'].str.upper()
dp2

      first   last      email
0    sohaib  awais      AHMAD
1  talha123  talha     MUMTAZ
2  saleh123  saleh  JAHANZAIB

> 4 ways to change multiplr rows:
- apply
- applymap
- map
- replace

In [41]:
dp2['email'].apply(len)

0    5
1    6
2    9
Name: email, dtype: int64

In [42]:
dp2['email'] = dp2['email'].apply(lambda x: x.lower())
dp2

      first   last      email
0    sohaib  awais      ahmad
1  talha123  talha     mumtaz
2  saleh123  saleh  jahanzaib

In [43]:
print(dp2.apply(pd.Series.max), end='\n.....................\n') #applies function to all series
print(dp2.apply(pd.Series.min))

first    talha123
last        talha
email      mumtaz
dtype: object
.....................
first    saleh123
last        awais
email       ahmad
dtype: object

In [44]:
dp2.applymap(len)

   first  last  email
0      6     5      5
1      8     5      6
2      8     5      9

In [45]:
dp2['first'].map({'awais':'sohaib'})

0    NaN
1    NaN
2    NaN
Name: first, dtype: object

In [46]:
dp2['first'].replace({'awais':'sohaib'})

0      sohaib
1    talha123
2    saleh123
Name: first, dtype: object

# Tutorial #6

In [47]:
dp2['full_name'] = dp2['first'] + " " + dp2['last']

In [48]:
dp2

      first   last      email       full_name
0    sohaib  awais      ahmad    sohaib awais
1  talha123  talha     mumtaz  talha123 talha
2  saleh123  saleh  jahanzaib  saleh123 saleh

In [49]:
dp2.drop(columns=['first','last'],inplace=True)
dp2

       email       full_name
0      ahmad    sohaib awais
1     mumtaz  talha123 talha
2  jahanzaib  saleh123 saleh

In [50]:
dp2[['first','last']] = dp2['full_name'].str.split(' ', expand=True)
dp2

       email       full_name     first   last
0      ahmad    sohaib awais    sohaib  awais
1     mumtaz  talha123 talha  talha123  talha
2  jahanzaib  saleh123 saleh  saleh123  saleh

In [51]:
filt = (dp2['last'].apply(len)==5 )| (dp2['last'].apply(len)==6)
dp2.drop(index=dp2[filt].index)

Empty DataFrame
Columns: [email, full_name, first, last]
Index: []

# Tutorial#7

In [56]:
dp2.sort_values(by='last')

       email       full_name     first   last
0      ahmad     awais ahmad     awais  ahmad
2  jahanzaib  saleh123 saleh  saleh123  saleh
1     mumtaz  talha123 talha  talha123  talha

In [57]:
# if 'last'(descending) is same then go for 'first'(ascending)
dp2.sort_values(by=['last','first'],ascending=[False,True], inplace=True)

In [58]:
dp2

       email       full_name     first   last
1     mumtaz  talha123 talha  talha123  talha
2  jahanzaib  saleh123 saleh  saleh123  saleh
0      ahmad     awais ahmad     awais  ahmad

In [60]:
dp2.sort_index(inplace=True)

In [64]:
dp2['first'].sort_values()     #Individual column sort

ValueError: This Series is a view of some other array, to sort in-place you must create a copy

# Stack Overflow

In [131]:
filt = (df['Country'].str.contains('Pak', na=False)) & df['CompFreq'].str.contains('Yearly', na=False)
df.loc[filt,['CompTotal','CompFreq','Currency']].sort_values(by=['CompTotal'],ascending=[False])

             CompTotal CompFreq                         Currency
ResponseId
16546       10000000.0   Yearly             PKR\tPakistani rupee
47896        9000000.0   Yearly             PKR\tPakistani rupee
72909        6000000.0   Yearly             PKR\tPakistani rupee
4728         5720000.0   Yearly             PKR\tPakistani rupee
8366         5000000.0   Yearly             PKR\tPakistani rupee
62437        4000000.0   Yearly             PKR\tPakistani rupee
60083        3600000.0   Yearly             PKR\tPakistani rupee
8016         3500000.0   Yearly             PKR\tPakistani rupee
62325        2640000.0   Yearly             PKR\tPakistani rupee
6949         2500000.0   Yearly             PKR\tPakistani rupee
62432        2080000.0   Yearly             PKR\tPakistani rupee
9170         1600000.0   Yearly             PKR\tPakistani rupee
27397        1200000.0   Yearly             PKR\tPakistani rupee
67561        1190000.0   Yearly             PKR\tPakistani rupee
9050         1100000.0   Yearly             PKR\tPakistani rupee
62433        1100000.0  Monthly             PKR\tPakistani rupee
67119        1050000.0  Monthly             PKR\tPakistani rupee
32356        1000000.0   Yearly             PKR\tPakistani rupee
72825        1000000.0  Monthly             PKR\tPakistani rupee
51747         700000.0  Monthly             PKR\tPakistani rupee
37114         700000.0  Monthly             PKR\tPakistani rupee
38893         700000.0   Yearly             PKR\tPakistani rupee
7203          700000.0   Yearly             PKR\tPakistani rupee
14924         600000.0  Monthly             PKR\tPakistani rupee
62434         600000.0  Monthly             PKR\tPakistani rupee
44712         600000.0  Monthly             PKR\tPakistani rupee
9465          550000.0  Monthly             PKR\tPakistani rupee
36186         550000.0  Monthly             PKR\tPakistani rupee
62417         540000.0  Monthly             PKR\tPakistani rupee
6989          500000.0  Monthly             PKR\tPakistani rupee
71905         500000.0  Monthly             PKR\tPakistani rupee
32747         480000.0  Monthly             PKR\tPakistani rupee
69111         460000.0  Monthly             PKR\tPakistani rupee
67619         450000.0  Monthly             PKR\tPakistani rupee
22961         407000.0   Weekly             PKR\tPakistani rupee
44282         400000.0  Monthly             PKR\tPakistani rupee
5746          400000.0  Monthly             PKR\tPakistani rupee
7292          400000.0  Monthly             PKR\tPakistani rupee
65255         400000.0  Monthly             PKR\tPakistani rupee
7605          370000.0  Monthly             PKR\tPakistani rupee
35690         370000.0  Monthly             PKR\tPakistani rupee
50964         370000.0  Monthly             PKR\tPakistani rupee
73029         360000.0  Monthly             PKR\tPakistani rupee
62665         350000.0  Monthly             PKR\tPakistani rupee
2918          350000.0  Monthly             PKR\tPakistani rupee
5080          350000.0  Monthly             PKR\tPakistani rupee
4980          320000.0  Monthly             PKR\tPakistani rupee
50291         314000.0  Monthly             PKR\tPakistani rupee
3831          300000.0  Monthly             PKR\tPakistani rupee
4082          300000.0  Monthly             PKR\tPakistani rupee
7851          300000.0  Monthly             PKR\tPakistani rupee
6022          300000.0  Monthly             PKR\tPakistani rupee
34993         300000.0  Monthly             PKR\tPakistani rupee
25416         300000.0  Monthly             PKR\tPakistani rupee
36468         300000.0  Monthly             PKR\tPakistani rupee
41927         300000.0  Monthly             PKR\tPakistani rupee
18475         300000.0  Monthly             PKR\tPakistani rupee
43486         300000.0  Monthly             PKR\tPakistani rupee
42286         280000.0  Monthly             PKR\tPakistani rupee
70261         270000.0  Monthly             PKR\tPakistani rupee
52342         260000.0  Monthly             PKR\tPakistani rupee
44341         250000.0  Monthly             PKR\tPakistani rupee
26174         250000.0  Monthly             PKR\tPakistani rupee
58749         250000.0  Monthly             PKR\tPakistani rupee
71657         250000.0  Monthly             PKR\tPakistani rupee
34399         250000.0  Monthly             PKR\tPakistani rupee
40947         250000.0  Monthly             PKR\tPakistani rupee
17220         240000.0   Yearly             PKR\tPakistani rupee
49171         230000.0  Monthly             PKR\tPakistani rupee
7969          230000.0  Monthly             PKR\tPakistani rupee
62435         220000.0  Monthly             PKR\tPakistani rupee
55998         220000.0  Monthly             PKR\tPakistani rupee
68722         216000.0  Monthly             PKR\tPakistani rupee
4881          200000.0  Monthly             PKR\tPakistani rupee
64594         200000.0  Monthly             PKR\tPakistani rupee
21010         200000.0  Monthly             PKR\tPakistani rupee
9272          200000.0  Monthly             PKR\tPakistani rupee
19646         200000.0  Monthly             PKR\tPakistani rupee
49186         200000.0  Monthly             PKR\tPakistani rupee
60134         200000.0  Monthly             PKR\tPakistani rupee
49818         200000.0  Monthly             PKR\tPakistani rupee
57704         200000.0  Monthly             PKR\tPakistani rupee
6753          200000.0  Monthly             PKR\tPakistani rupee
54810         190000.0  Monthly             PKR\tPakistani rupee
23572         190000.0  Monthly             PKR\tPakistani rupee
4146          190000.0  Monthly             PKR\tPakistani rupee
7169          180000.0  Monthly             PKR\tPakistani rupee
33042         180000.0  Monthly             PKR\tPakistani rupee
10036         175000.0  Monthly             PKR\tPakistani rupee
26345         175000.0  Monthly             PKR\tPakistani rupee
71168         170000.0  Monthly             PKR\tPakistani rupee
70739         170000.0   Yearly        USD\tUnited States dollar
20005         160000.0  Monthly             PKR\tPakistani rupee
31249         160000.0  Monthly             PKR\tPakistani rupee
28974         160000.0  Monthly             PKR\tPakistani rupee
57418         160000.0  Monthly             PKR\tPakistani rupee
52779         150000.0   Yearly             PKR\tPakistani rupee
67063         150000.0  Monthly             PKR\tPakistani rupee
60582         150000.0  Monthly             PKR\tPakistani rupee
42823         150000.0  Monthly             PKR\tPakistani rupee
62361         150000.0  Monthly             PKR\tPakistani rupee
28103         150000.0  Monthly             PKR\tPakistani rupee
71212         150000.0  Monthly             PKR\tPakistani rupee
917           150000.0  Monthly             PKR\tPakistani rupee
22497         150000.0  Monthly             PKR\tPakistani rupee
4100          150000.0  Monthly             PKR\tPakistani rupee
23237         150000.0  Monthly             PKR\tPakistani rupee
13592         145000.0  Monthly             PKR\tPakistani rupee
34172         141000.0  Monthly             PKR\tPakistani rupee
29383         135000.0  Monthly             PKR\tPakistani rupee
33095         135000.0  Monthly             PKR\tPakistani rupee
18532         130000.0  Monthly             PKR\tPakistani rupee
5237          130000.0  Monthly             PKR\tPakistani rupee
34848         130000.0  Monthly             PKR\tPakistani rupee
8195          130000.0  Monthly             PKR\tPakistani rupee
42526         130000.0  Monthly             PKR\tPakistani rupee
51006         130000.0  Monthly             PKR\tPakistani rupee
57936         129950.0  Monthly             PKR\tPakistani rupee
21473         126000.0  Monthly             PKR\tPakistani rupee
52233         125000.0  Monthly             PKR\tPakistani rupee
47926         125000.0  Monthly             PKR\tPakistani rupee
9031          125000.0  Monthly             PKR\tPakistani rupee
56974         120000.0  Monthly             PKR\tPakistani rupee
36112         120000.0   Yearly        USD\tUnited States dollar
10010         120000.0      NaN             PKR\tPakistani rupee
33147         120000.0  Monthly             PKR\tPakistani rupee
17021         120000.0  Monthly             PKR\tPakistani rupee
49677         120000.0  Monthly             PKR\tPakistani rupee
18712         115000.0  Monthly             PKR\tPakistani rupee
43886         115000.0  Monthly             PKR\tPakistani rupee
46694         115000.0  Monthly             PKR\tPakistani rupee
49612         110000.0  Monthly             PKR\tPakistani rupee
9096          110000.0  Monthly             PKR\tPakistani rupee
47822         110000.0  Monthly             PKR\tPakistani rupee
42551         106000.0  Monthly             PKR\tPakistani rupee
57272         105000.0   Yearly             PKR\tPakistani rupee
33331         100000.0  Monthly             PKR\tPakistani rupee
18774         100000.0  Monthly             PKR\tPakistani rupee
28508         100000.0  Monthly             PKR\tPakistani rupee
56794         100000.0  Monthly             PKR\tPakistani rupee
56003         100000.0  Monthly             PKR\tPakistani rupee
18741         100000.0  Monthly             PKR\tPakistani rupee
28213         100000.0  Monthly             PKR\tPakistani rupee
23497         100000.0  Monthly             PKR\tPakistani rupee
35737         100000.0  Monthly             PKR\tPakistani rupee
26467         100000.0  Monthly             PKR\tPakistani rupee
72001         100000.0  Monthly             PKR\tPakistani rupee
49683         100000.0  Monthly             PKR\tPakistani rupee
3510          100000.0  Monthly             PKR\tPakistani rupee
49656         100000.0  Monthly             PKR\tPakistani rupee
25800         100000.0  Monthly             PKR\tPakistani rupee
46287         100000.0  Monthly             PKR\tPakistani rupee
25777         100000.0  Monthly             PKR\tPakistani rupee
58705         100000.0  Monthly             PKR\tPakistani rupee
16836         100000.0  Monthly             PKR\tPakistani rupee
8491          100000.0  Monthly             PKR\tPakistani rupee
64537         100000.0  Monthly             PKR\tPakistani rupee
60944         100000.0  Monthly             PKR\tPakistani rupee
32471         100000.0  Monthly             PKR\tPakistani rupee
32669         100000.0  Monthly             PKR\tPakistani rupee
62578         100000.0  Monthly             PKR\tPakistani rupee
32664         100000.0  Monthly             PKR\tPakistani rupee
65752         100000.0  Monthly             PKR\tPakistani rupee
21110         100000.0  Monthly             PKR\tPakistani rupee
16623          98000.0  Monthly             PKR\tPakistani rupee
65475          98000.0  Monthly             PKR\tPakistani rupee
18455          90000.0  Monthly             PKR\tPakistani rupee
42164          90000.0  Monthly             PKR\tPakistani rupee
29404          90000.0  Monthly             PKR\tPakistani rupee
7411           85000.0  Monthly             PKR\tPakistani rupee
9188           85000.0  Monthly             PKR\tPakistani rupee
60587          85000.0  Monthly             PKR\tPakistani rupee
63306          85000.0  Monthly             PKR\tPakistani rupee
6181           85000.0  Monthly             PKR\tPakistani rupee
7496           85000.0  Monthly             PKR\tPakistani rupee
17315          80000.0  Monthly             PKR\tPakistani rupee
18239          80000.0  Monthly             PKR\tPakistani rupee
29691          80000.0  Monthly             PKR\tPakistani rupee
30018          80000.0  Monthly             PKR\tPakistani rupee
28150          80000.0   Yearly             PKR\tPakistani rupee
5367           80000.0  Monthly             PKR\tPakistani rupee
29541          80000.0  Monthly             PKR\tPakistani rupee
69207          80000.0  Monthly             PKR\tPakistani rupee
35828          80000.0  Monthly             PKR\tPakistani rupee
5911           80000.0  Monthly             PKR\tPakistani rupee
35430          80000.0  Monthly             PKR\tPakistani rupee
59202          80000.0  Monthly             PKR\tPakistani rupee
9712           80000.0  Monthly             PKR\tPakistani rupee
30020          80000.0   Yearly             PKR\tPakistani rupee
71433          75000.0  Monthly             PKR\tPakistani rupee
56311          75000.0  Monthly             PKR\tPakistani rupee
8365           75000.0  Monthly             PKR\tPakistani rupee
7171           75000.0  Monthly             PKR\tPakistani rupee
29700          75000.0  Monthly             PKR\tPakistani rupee
3045           72000.0  Monthly             PKR\tPakistani rupee
32724          72000.0  Monthly             PKR\tPakistani rupee
4552           70000.0  Monthly             PKR\tPakistani rupee
49676          70000.0  Monthly             PKR\tPakistani rupee
67850          70000.0  Monthly             PKR\tPakistani rupee
65413          70000.0  Monthly             PKR\tPakistani rupee
49877          70000.0  Monthly             PKR\tPakistani rupee
8761           70000.0  Monthly             PKR\tPakistani rupee
4675           60000.0  Monthly             PKR\tPakistani rupee
63027          60000.0  Monthly             PKR\tPakistani rupee
15055          60000.0  Monthly             PKR\tPakistani rupee
10442          60000.0  Monthly             PKR\tPakistani rupee
68851          60000.0  Monthly             PKR\tPakistani rupee
68755          60000.0  Monthly             PKR\tPakistani rupee
56301          60000.0  Monthly             PKR\tPakistani rupee
69153          55000.0  Monthly             PKR\tPakistani rupee
32650          55000.0  Monthly             PKR\tPakistani rupee
24227          55000.0  Monthly             PKR\tPakistani rupee
32736          55000.0  Monthly             PKR\tPakistani rupee
43544          52500.0  Monthly             PKR\tPakistani rupee
20547          50000.0  Monthly             PKR\tPakistani rupee
33208          50000.0  Monthly             PKR\tPakistani rupee
11749          50000.0  Monthly             PKR\tPakistani rupee
58910          50000.0  Monthly             PKR\tPakistani rupee
28042          50000.0  Monthly             PKR\tPakistani rupee
18743          50000.0  Monthly             PKR\tPakistani rupee
71220          50000.0  Monthly             PKR\tPakistani rupee
67512          50000.0  Monthly             PKR\tPakistani rupee
13092          50000.0  Monthly             PKR\tPakistani rupee
23067          50000.0  Monthly        USD\tUnited States dollar
71294          50000.0  Monthly             PKR\tPakistani rupee
58275          48000.0   Yearly                EUR European Euro
48984          45000.0  Monthly             PKR\tPakistani rupee
17218          45000.0  Monthly             PKR\tPakistani rupee
33513          45000.0  Monthly             PKR\tPakistani rupee
5908           45000.0  Monthly             PKR\tPakistani rupee
29331          45000.0  Monthly             PKR\tPakistani rupee
45847          40000.0  Monthly             PKR\tPakistani rupee
49260          40000.0  Monthly             PKR\tPakistani rupee
27902          40000.0  Monthly             PKR\tPakistani rupee
61488          40000.0  Monthly             PKR\tPakistani rupee
6695           35000.0   Yearly        USD\tUnited States dollar
8856           35000.0  Monthly             PKR\tPakistani rupee
22942          35000.0  Monthly             PKR\tPakistani rupee
18870          35000.0  Monthly             PKR\tPakistani rupee
32534          35000.0  Monthly             PKR\tPakistani rupee
18913          35000.0  Monthly             PKR\tPakistani rupee
37954          35000.0  Monthly             PKR\tPakistani rupee
23534          35000.0  Monthly             PKR\tPakistani rupee
26382          35000.0  Monthly             PKR\tPakistani rupee
27272          30000.0   Yearly        USD\tUnited States dollar
32377          30000.0  Monthly             PKR\tPakistani rupee
25608          30000.0  Monthly             PKR\tPakistani rupee
60167          30000.0  Monthly             PKR\tPakistani rupee
60559          30000.0  Monthly             PKR\tPakistani rupee
41997          30000.0  Monthly             PKR\tPakistani rupee
55159          25000.0  Monthly        USD\tUnited States dollar
11969          25000.0  Monthly             PKR\tPakistani rupee
49408          20000.0   Yearly        USD\tUnited States dollar
57997          20000.0  Monthly             PKR\tPakistani rupee
71367          17000.0   Yearly           AUD\tAustralian dollar
28893          17000.0  Monthly             PKR\tPakistani rupee
24501          15000.0  Monthly  AED United Arab Emirates dirham
25487          15000.0  Monthly             PKR\tPakistani rupee
32620          15000.0  Monthly             PKR\tPakistani rupee
28579           6800.0  Monthly        USD\tUnited States dollar
46449           6600.0  Monthly        USD\tUnited States dollar
46066           6250.0  Monthly             CAD\tCanadian dollar
16595           5000.0  Monthly        USD\tUnited States dollar
60786           5000.0  Monthly  AED United Arab Emirates dirham
56686           4800.0  Monthly        USD\tUnited States dollar
68591           4000.0  Monthly        USD\tUnited States dollar
14920           3500.0  Monthly        USD\tUnited States dollar
68098           3200.0  Monthly        USD\tUnited States dollar
37413           3000.0  Monthly        USD\tUnited States dollar
1391            2500.0  Monthly        USD\tUnited States dollar
72869           2260.0  Monthly             PKR\tPakistani rupee
58690           2000.0      NaN        USD\tUnited States dollar
35155           2000.0  Monthly        USD\tUnited States dollar
36857           1800.0  Monthly        USD\tUnited States dollar
7834            1600.0  Monthly        USD\tUnited States dollar
11092           1500.0  Monthly        USD\tUnited States dollar
29023           1300.0  Monthly        USD\tUnited States dollar
20496           1200.0  Monthly        USD\tUnited States dollar
48773           1000.0  Monthly        USD\tUnited States dollar
28513           1000.0  Monthly              GBP\tPound sterling
17288            975.0  Monthly        USD\tUnited States dollar
45058            900.0  Monthly        USD\tUnited States dollar
63171            900.0   Yearly             PKR\tPakistani rupee
69918            800.0  Monthly        USD\tUnited States dollar
16439            700.0  Monthly        USD\tUnited States dollar
11650            600.0  Monthly        USD\tUnited States dollar
28547            600.0  Monthly        USD\tUnited States dollar
35001            500.0  Monthly        USD\tUnited States dollar
32484            450.0  Monthly        USD\tUnited States dollar
32613            450.0  Monthly             PKR\tPakistani rupee
18052            350.0  Monthly        USD\tUnited States dollar
11974            150.0  Monthly             PKR\tPakistani rupee
9137              60.0  Monthly             PKR\tPakistani rupee
32449             30.0  Monthly             PKR\tPakistani rupee
8691               0.0  Monthly         SAR\tSaudi Arabian riyal
1199               NaN      NaN                              NaN
3554               NaN  Monthly             PKR\tPakistani rupee
3586               NaN      NaN                              NaN
3599               NaN  Monthly             PKR\tPakistani rupee
3695               NaN      NaN             PKR\tPakistani rupee
3788               NaN  Monthly             PKR\tPakistani rupee
3841               NaN  Monthly             PKR\tPakistani rupee
3961               NaN      NaN             PKR\tPakistani rupee
4039               NaN      NaN                              NaN
4327               NaN      NaN             PKR\tPakistani rupee
4355               NaN      NaN             PKR\tPakistani rupee

In [160]:
filt = df['Currency'].str.contains('USD', na=False)
df.loc[filt,['Employment','EdLevel','YearsCode','YearsCodePro','DevType','CompTotal','CompFreq','LanguageHaveWorkedWith','Ethnicity']].nlargest(100,'CompTotal')

,Employment,EdLevel,YearsCode,YearsCodePro,DevType,CompTotal,CompFreq,LanguageHaveWorkedWith,Ethnicity
ResponseId,,,,,,,,,
3069,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",10,2,"Developer, back-end;Scientist",1.000000e+52,Weekly,C;C++;Fortran;Java;Python;Scala,"Or, in your own words:"
31191,"Employed, full-time","Other doctoral degree (Ph.D., Ed.D., etc.)",10,Less than 1 year,Data scientist or machine learning specialist;...,1.000000e+12,Monthly,APL;Assembly;Bash/Shell;C;C#;C++;Clojure;COBOL...,White;Indian;European;North American;Middle Ea...
71604,"Employed, part-time",Something else,4,NaN,Scientist,9.363220e+09,Monthly,APL,Asian
62108,"Employed, full-time;Independent contractor, fr...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",20,15,Data scientist or machine learning specialist;...,1.905600e+08,Yearly,Assembly;Bash/Shell;C;C#;C++;Dart;Go;HTML/CSS;...,White;East Asian
44886,"Employed, full-time",Some college/university study without earning ...,13,12,"Developer, back-end",1.508000e+08,Yearly,C#;Go,Hispanic or Latino/a
1889,"Independent contractor, freelancer, or self-em...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",30,15,Other (please specify):,1.200000e+07,Yearly,Bash/Shell;C++;HTML/CSS;Java;Python;SQL,White
118,"Employed, full-time;Independent contractor, fr...",Some college/university study without earning ...,32,28,Data scientist or machine learning specialist;...,6.000000e+06,Yearly,C#,Prefer not to say
14370,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6,5,"Developer, full-stack",2.520000e+06,Yearly,Haskell;HTML/CSS;Java;JavaScript;Python;SQL;Ty...,Asian
32447,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",13,16,"Developer, full-stack;Developer, mobile",2.100000e+06,Yearly,Bash/Shell;C#;C++;HTML/CSS;JavaScript;MATLAB;P...,Indian
24477,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6,4,"Developer, back-end",2.000000e+06,Yearly,Go;Java;JavaScript;Python;SQL,Indian
68515,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",20,12,"Developer, front-end",2.000000e+06,Yearly,C;C#;Java;Kotlin;PHP,North American
50535,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18,10,"Developer, back-end",1.850000e+06,Yearly,C#,White
1941,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",33,20,"Developer, full-stack;Developer, back-end;Deve...",1.750000e+06,Yearly,Bash/Shell;HTML/CSS;JavaScript;Lua;Ruby;SQL;Ty...,White
30328,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",12,8,"Developer, front-end;Developer, full-stack",1.680000e+06,Yearly,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript,Asian
63412,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5,15,"Developer, back-end;Cloud infrastructure engineer",1.600000e+06,Yearly,Bash/Shell;C;C++;Go;Python;Rust,White
22419,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",20,15,"Engineer, data;Engineer, site reliability;Deve...",1.500000e+06,Yearly,Bash/Shell;Go;Ruby,White;South American
25354,"Employed, full-time",Some college/university study without earning ...,37,30,"Developer, back-end;Engineering manager;Projec...",1.500000e+06,Yearly,Assembly;Bash/Shell;C++;Python,White
3233,"Independent contractor, freelancer, or self-em...",Some college/university study without earning ...,17,11,"Developer, full-stack;Database administrator;C...",1.440000e+06,Yearly,Bash/Shell;HTML/CSS;JavaScript;Ruby;SQL,European
16164,"Employed, part-time","Other doctoral degree (Ph.D., Ed.D., etc.)",8,4,Data scientist or machine learning specialist;...,1.250000e+06,Yearly,Bash/Shell;C#;HTML/CSS;Java;JavaScript;Julia;K...,Asian
62166,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",41,30,"Developer, front-end;Developer, full-stack;Dev...",1.250000e+06,Yearly,C;C++;Delphi,Pacific Islander
20457,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",25,22,Product manager,1.200000e+06,Yearly,Bash/Shell;C;C#;C++;Java;JavaScript;Python;Rus...,White
58899,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5,5,Data scientist or machine learning specialist;...,1.200000e+06,Yearly,F#,White
72195,"Employed, full-time",Some college/university study without earning ...,28,20,"Engineer, site reliability;Developer, back-end",1.100000e+06,Yearly,Bash/Shell;Go;PHP;PowerShell;Python;Ruby;Rust;SQL,White;African
1383,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",19,10,"Developer, back-end",1.050000e+06,Yearly,C;C++;Rust,White
1517,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",23,23,"Developer, full-stack;Developer, desktop or en...",1.000000e+06,Yearly,C++;Groovy;HTML/CSS;JavaScript;Python,White;European;Indigenous (such as Native Amer...
12452,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",30,20,"Senior Executive (C-Suite, VP, etc.)",1.000000e+06,Yearly,C;C#;Go;HTML/CSS;Java;TypeScript,White
28010,"Employed, full-time;Independent contractor, fr...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",32,30,"Senior Executive (C-Suite, VP, etc.)",1.000000e+06,Yearly,Bash/Shell;C#;Elixir;Go;HTML/CSS;JavaScript;Lu...,Middle Eastern
39799,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",More than 50 years,49,"Developer, desktop or enterprise applications;...",1.000000e+06,Yearly,C#;SQL,White
40305,"Independent contractor, freelancer, or self-em...","Secondary school (e.g. American high school, G...",Less than 1 year,2,"Engineer, data;Engineer, site reliability;Deve...",1.000000e+06,Weekly,APL;Assembly;Bash/Shell;C;C#;C++;COBOL;Crystal...,Central Asian
40882,"Employed, full-time",Some college/university study without earning ...,25,14,Other (please specify):,1.000000e+06,Yearly,C;C++;SQL,Asian
52024,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",12,8,"Developer, back-end",1.000000e+06,Yearly,Go;Java;JavaScript;Kotlin;Python;TypeScript,White
71857,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",25,15,"Developer, back-end;Engineering manager",1.000000e+06,Yearly,C;C++;HTML/CSS;JavaScript;Ruby;SQL,White
1875,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",3,1,Data scientist or machine learning specialist;...,9.560000e+05,Yearly,F#;Python;R;VBA,White
3382,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",13,8,Data scientist or machine learning specialist;...,9.500000e+05,Yearly,Bash/Shell;C++;Python;R,White;North American
62129,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",6,3,"Developer, front-end;Designer",9.450000e+05,Yearly,HTML/CSS;JavaScript;Python;TypeScript,White
2748,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",22,12,Engineering manager,9.300000e+05,Yearly,C#;HTML/CSS;JavaScript;Rust;TypeScript,White
13456,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",26,23,"Developer, back-end;Engineering manager",9.000000e+05,Yearly,Bash/Shell;HTML/CSS;Java;JavaScript;SQL,White
25683,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",24,20,"Engineer, site reliability;Developer, back-end...",9.000000e+05,Yearly,C#;HTML/CSS;JavaScript;SQL;TypeScript,White
50502,"Employed, full-time",Some college/university study without earning ...,28,23,"Developer, full-stack;Cloud infrastructure eng...",8.900000e+05,Yearly,Clojure;Go;JavaScript;Python;TypeScript,White
4867,"Employed, full-time",Some college/university study without earning ...,10,7,"Developer, front-end;Developer, full-stack;Dev...",8.500000e+05,Yearly,Bash/Shell;C#;JavaScript;SQL;TypeScript,White
7888,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33,32,"Developer, full-stack;Senior Executive (C-Suit...",8.500000e+05,Yearly,Go;JavaScript;Rust;TypeScript,White
11912,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",31,21,"Developer, full-stack",8.280000e+05,Yearly,Bash/Shell;JavaScript;Ruby,White
29688,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",10,8,"Engineer, site reliability",8.000000e+05,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,White
44384,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11,6,"Developer, front-end;Developer, full-stack;Dev...",8.000000e+05,Yearly,C;C#;C++;Crystal;HTML/CSS;Java;JavaScript;PHP;SQL,Indian;Asian;South Asian
56354,"Employed, full-time;Independent contractor, fr...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",48,38,"Product manager;Senior Executive (C-Suite, VP,...",8.000000e+05,Yearly,Bash/Shell;HTML/CSS;Java;JavaScript;SQL,White
70515,"Independent contractor, freelancer, or self-em...",Primary/elementary school,NaN,7,"Engineer, data;Engineer, site reliability;Deve...",7.870000e+05,Yearly,Bash/Shell;C#;Go;Groovy;Java;JavaScript;Python...,Indian;Asian;Southeast Asian
1842,"Employed, full-time","Other doctoral degree (Ph.D., Ed.D., etc.)",13,7,Blockchain,7.830000e+05,Monthly,C;C++;Rust,White;European
23144,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",16,12,"Developer, back-end;Cloud infrastructure engineer",7.650000e+05,Yearly,Java,Indian
15992,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",13,10,Data scientist or machine learning specialist;...,7.600000e+05,Yearly,Clojure;Java;Scala,European
551,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",8,6,NaN,7.500000e+05,Yearly,Python;SQL,White
2861,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",10,5,Other (please specify):,7.500000e+05,Yearly,Python;Rust,White
27643,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",26,22,"Engineer, data;Developer, full-stack;Developer...",7.500000e+05,Yearly,Bash/Shell;C#;JavaScript;Python;Rust;SQL,White;North American
31176,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15,10,"Engineer, data;Developer, back-end;Database ad...",7.500000e+05,Yearly,Bash/Shell;Go;SQL;TypeScript,White;North American
45931,"Employed, full-time",Some college/university study without earning ...,9,7,"Developer, mobile",7.500000e+05,Yearly,Bash/Shell;Groovy;Java;Kotlin,White
46107,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",22,NaN,Engineering manager,7.500000e+05,Yearly,Go;Java;JavaScript;SQL;TypeScript,European
57156,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",45,39,"Developer, back-end",7.500000e+05,Yearly,C++;Python,White
20123,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",24,18,"Developer, back-end",7.200000e+05,Yearly,Bash/Shell;JavaScript;Python;SQL;TypeScript,White
2721,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",20,20,Engineering manager,7.000000e+05,Yearly,JavaScript;Kotlin;Python,White
22723,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",40,10,"Senior Executive (C-Suite, VP, etc.)",7.000000e+05,Yearly,C;Go;Python;Ruby;SQL,European
22882,"Employed, full-time","Other doctoral degree (Ph.D., Ed.D., etc.)",12,7,Data scientist or machine learning specialist;...,7.000000e+05,Yearly,Python;Scala;SQL,European
46771,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",12,11,"Developer, front-end;Developer, full-stack;Dev...",7.000000e+05,Yearly,Bash/Shell;Go;HTML/CSS;Java;JavaScript;Python;...,White
51342,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",35,22,"Engineer, site reliability;Developer, back-end...",7.000000e+05,Yearly,Bash/Shell;Groovy;Java;JavaScript;Python;SQL,White
59197,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",10,9,"Developer, back-end",7.000000e+05,Yearly,Elixir;Kotlin,Asian
62027,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6,1,"Developer, front-end;Developer, full-stack;Dev...",7.000000e+05,Weekly,Bash/Shell;Go;JavaScript;TypeScript,Asian
63806,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6,2,Data scientist or machine learning specialist;...,7.000000e+05,Yearly,C#;C++;Dart;JavaScript;MATLAB;PowerShell;Pytho...,White
47840,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25,22,"Developer, full-stack;Developer, desktop or en...",6.750000e+05,Yearly,C#;JavaScript;Python;SQL;TypeScript,White
1058,"Employed, full-time",Some college/university study without earning ...,15,15,"Developer, front-end;Engineer, site reliabilit...",6.500000e+05,Yearly,C;C#;C++;Clojure;Go;HTML/CSS;Java;JavaScript;P...,White
3225,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",16,10,"Developer, full-stack;Developer, back-end;Secu...",6.500000e+05,Yearly,Bash/Shell;C;C++;Erlang;Groovy;Kotlin;Python;Rust,White;European;North American
13783,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",45,38,"Developer, back-end;DevOps specialist",6.500000e+05,Yearly,Python,NaN
16079,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",30,18,"Developer, embedded applications or devices",6.500000e+05,Yearly,Assembly;Bash/Shell;C;C++,White
20372,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",35,30,"Developer, back-end;Educator;Cloud infrastruct...",6.500000e+05,Yearly,Bash/Shell;Clojure;Java,White;European;North American
20666,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",14,12,"Developer, front-end",6.500000e+05,Yearly,HTML/CSS;JavaScript;Rust;Swift;TypeScript,White
52213,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",16,14,"Developer, full-stack;Project manager",6.500000e+05,Yearly,C#,Hispanic or Latino/a
56015,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",23,19,"Senior Executive (C-Suite, VP, etc.)",6.500000e+05,Yearly,Bash/Shell;C#;C++;HTML/CSS;Java;JavaScript;R;SQL,White
66316,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",49,47,"Developer, desktop or enterprise applications;...",6.500000e+05,Yearly,Assembly;C++,White
70523,"Independent contractor, freelancer, or self-em...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",22,10,"Engineer, site reliability;DevOps specialist;C...",6.500000e+05,Weekly,Bash/Shell;Go;JavaScript;Python;SQL,European;Central American;Hispanic or Latino/a
31306,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",17,13,"Developer, mobile",6.370000e+05,Yearly,C++;Dart;Elixir;HTML/CSS;Java;JavaScript;Objec...,White
27181,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",24,12,"Engineer, data;Engineer, site reliability;Deve...",6.330000e+05,Yearly,Go;HTML/CSS;Ruby,East Asian
16593,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25,20,Other (please specify):,6.300000e+05,Yearly,Bash/Shell;C;C++;Python;TypeScript,White
46844,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",26,13,"Developer, back-end;Developer, mobile;Engineer...",6.280000e+05,Yearly,Java;Kotlin;Python;Ruby;Scala;Swift,White;Hispanic or Latino/a
68084,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",22,20,"Developer, back-end",6.231880e+05,Yearly,C#;Go;Java;SQL,White;North American;African;Biracial
1418,"Employed, part-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",30,18,"Developer, embedded applications or devices",6.200000e+05,Yearly,Bash/Shell;C;C++;Go;Python;Rust,White
22814,"Employed, full-time","Professional degree (JD, MD, etc.)",11,11,Engineering manager,6.102050e+05,Yearly,Elixir;Ruby,White;Multiracial
45991,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",15,12,"Engineer, data;Developer, back-end;Developer, ...",6.050000e+05,Yearly,Bash/Shell;Go;Java;Python;Scala;SQL,Prefer not to say
2779,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15,6,"Developer, full-stack;Developer, mobile",6.000000e+05,Yearly,HTML/CSS;Java;JavaScript;Python;Ruby;SQL;Swift...,White
3079,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",22,20,DevOps specialist;Other (please specify):,6.000000e+05,Yearly,Assembly;COBOL;Java;JavaScript;Kotlin;Python;S...,Indian
14342,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",20,15,"Developer, back-end",6.000000e+05,Yearly,C;Go;Java;Kotlin;Python;Ruby;Rust,White
14636,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",9,9,Other (please specify):,6.000000e+05,Yearly,Haskell;Julia;MATLAB;Python;R;Rust;SQL;VBA,White
21886,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",16,11,"Developer, mobile",6.000000e+05,Yearly,Java;Kotlin;Python;Ruby;TypeScript,White
22407,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",30,30,Product manager,6.000000e+05,Yearly,Bash/Shell;C#;HTML/CSS;JavaScript;PowerShell;P...,NaN
45328,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18,11,"Engineer, data;Developer, back-end;Engineering...",6.000000e+05,Yearly,Bash/Shell;C#;Groovy;Java;JavaScript;Kotlin;Py...,White
50298,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",9,9,"Engineer, data;Developer, mobile;Cloud infrast...",6.000000e+05,Yearly,C++;HTML/CSS;Java;Objective-C;Python;SQL,White
72629,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",30,17,"Developer, back-end",6.000000e+05,Yearly,Bash/Shell;Go;HTML/CSS;OCaml;SQL,Indian;Asian;South Asian
4238,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15,7,"Developer, back-end",5.750000e+05,Yearly,Assembly;Bash/Shell;C;C++;Go;Python;SQL,White
48041,"Employed, full-time","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",23,15,"Developer, back-end;Cloud infrastructure engineer",5.600000e+05,Yearly,Assembly;Bash/Shell;C;Groovy;Haskell;HTML/CSS;...,European
69235,I prefer not to say,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",17,16,NaN,5.555550e+05,Yearly,Bash/Shell;C;C++,White
2263,"Employed, full-time",Some college/university study without earning ...,20,16,"Developer, back-end;Cloud infrastructure engineer",5.500000e+05,Yearly,Python;Rust,White;European;Hispanic or Latino/a;South Amer...
8551,"Employed, full-time",Some college/university study without earning ...,50,40,"Developer, back-end;Developer, QA or test;Data...",5.500000e+05,Yearly,Assembly;Bash/Shell;C;C++;Go;HTML/CSS;Java;Jav...,White
24645,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",42,38,"Developer, back-end;Security professional",5.500000e+05,Yearly,Bash/Shell;C++;Go;Python;SQL,NaN
31341,"Independent contractor, freelancer, or self-em...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",25,15,"Developer, front-end;Engineer, site reliabilit...",5.500000e+05,Yearly,Bash/Shell;Go;HTML/CSS;JavaScript;Python;SQL;T...,White

In [163]:
df.loc[40305]

MainBranch                                           I am a developer by profession
Employment                        Independent contractor, freelancer, or self-em...
RemoteWork                                                           Full in-person
CodingActivities                                            Freelance/contract work
EdLevel                           Secondary school (e.g. American high school, G...
LearnCode                         Other online resources (e.g., videos, blogs, f...
LearnCodeOnline                   Blogs;Stack Overflow;Online books;Video-based ...
LearnCodeCoursesCert                                                            NaN
YearsCode                                                          Less than 1 year
YearsCodePro                                                                      2
DevType                           Engineer, data;Engineer, site reliability;Deve...
OrgSize                                                    5,000 to 9,999 employees
PurchaseInfluence                                  I have a great deal of influence
BuyNewTool                        Other (please specify):;Visit developer commun...
Country                           United Kingdom of Great Britain and Northern I...
Currency                                                  USD\tUnited States dollar
CompTotal                                                                 1000000.0
CompFreq                                                                     Weekly
LanguageHaveWorkedWith            APL;Assembly;Bash/Shell;C;C#;C++;COBOL;Crystal...
LanguageWantToWorkWith                                                          NaN
DatabaseHaveWorkedWith            Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...
DatabaseWantToWorkWith                                                          NaN
PlatformHaveWorkedWith            AWS;Colocation;Firebase;Google Cloud;Heroku;IB...
PlatformWantToWorkWith                                                          NaN
WebframeHaveWorkedWith            Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...
WebframeWantToWorkWith                                                          NaN
MiscTechHaveWorkedWith            .NET;Apache Kafka;Capacitor;Cordova;Electron;F...
MiscTechWantToWorkWith                                                          NaN
ToolsTechHaveWorkedWith           Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...
ToolsTechWantToWorkWith                                                         NaN
NEWCollabToolsHaveWorkedWith      Android Studio;Atom;CLion;Eclipse;Emacs;GoLand...
NEWCollabToolsWantToWorkWith                                                    NaN
OpSysProfessional use                                       Other (please specify):
OpSysPersonal use                 Linux-based;macOS;Windows;Windows Subsystem fo...
VersionControlSystem                      Git;Other (please specify):;Mercurial;SVN
VCInteraction                     Code editor;Command-line;Version control hosti...
VCHostingPersonal use                                                           NaN
VCHostingProfessional use                                                       NaN
OfficeStackAsyncHaveWorkedWith    Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...
OfficeStackAsyncWantToWorkWith                                                  NaN
OfficeStackSyncHaveWorkedWith     Cisco Webex Teams;Coolfire Core;Google Chat;Ma...
OfficeStackSyncWantToWorkWith                                                   NaN
Blockchain                                                           Very favorable
NEWSOSites                        Collectives on Stack Overflow;Stack Overflow;S...
SOVisitFreq                                                   Daily or almost daily
SOAccount                                                                       Yes
SOPartFreq                                                    Daily or almost daily
SOComm                                                              Yes, definitely
Age                                                                 25-34 years old
Gender                                                            Prefer not to say
Trans                                                             Prefer not to say
Sexuality                                                         Prefer not to say
Ethnicity                                                             Central Asian
Accessibility                                                     Prefer not to say
MentalHealth                                                      Prefer not to say
TBranch                                                                         Yes
ICorPM                                                      Independent contributor
WorkExp                                                                        11.0
Knowledge_1                                                                   Agree
Knowledge_2                                                                   Agree
Knowledge_3                                                                   Agree
Knowledge_4                                                                   Agree
Knowledge_5                                                                   Agree
Knowledge_6                                                                   Agree
Knowledge_7                                                                   Agree
Frequency_1                                                        10+ times a week
Frequency_2                                                        3-5 times a week
Frequency_3                                                       6-10 times a week
TimeSearching                                                  60-120 minutes a day
TimeAnswering                                                  60-120 minutes a day
Onboarding                                                                Very long
ProfessionalTech                  Innersource initiative;DevOps function;Develop...
TrueFalse_1                                                                     Yes
TrueFalse_2                                                                     Yes
TrueFalse_3                                                                     Yes
SurveyLength                                                  Appropriate in length
SurveyEase                                                                     Easy
ConvertedCompYearly                                                      50000000.0
Name: 40305, dtype: object

In [164]:
df.nlargest(10,'CompTotal')

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
35787,I am a developer by profession,"Employed, full-time;Employed, part-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Secondary school (e.g. American high school, G...",Colleague,NaN,NaN,4,16,"Developer, full-stack;Academic researcher","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Visit developer communities like Stack Overflow,Ecuador,DOP\tDominican peso,9.000000e+56,Weekly,APL;COBOL;Scala,C++;Dart;MATLAB;VBA,IBM DB2,Neo4j;Redis,DigitalOcean,Heroku,Angular,Blazor;Svelte,Scikit-learn,Tidyverse,Puppet,Yarn,Android Studio,Android Studio,Windows,BSD,Other (please specify):;Mercurial,Command-line,NaN,NaN,Airtable,Planview Projectplace or Clarizen,Google Chat,RingCentral,Indifferent,Stack Overflow for Teams (private knowledge sh...,A few times per week,No,NaN,"No, not really",65 years or older,"Man;Woman;Non-binary, genderqueer, or gender n...",No,Straight / Heterosexual,White;Indian;European;North American;Middle Ea...,I am deaf / hard of hearing;I am blind / have ...,"I have a mood or emotional disorder (e.g., dep...",Yes,People manager,50.0,Disagree,Neither agree nor disagree,Agree,Strongly agree,Agree,Neither agree nor disagree,Disagree,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,Over 120 minutes a day,Just right,DevOps function;Automated testing,Yes,No,Yes,Too long,Difficult,NaN
3069,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc);Other ...",NaN,NaN,10,2,"Developer, back-end;Scientist","10,000 or more employees",I have some influence,NaN,United States of America,USD\tUnited States dollar,1.000000e+52,Weekly,C;C++;Fortran;Java;Python;Scala,Python;Rust;Scala,Cassandra;PostgreSQL;Redis;SQLite,Cassandra;PostgreSQL;Redis;SQLite,AWS,NaN,Flask,Flask,Apache Kafka;Apache Spark,Apache Kafka;Apache Spark,Docker;Kubernetes,Docker;Kubernetes,IntelliJ;PyCharm;Vim,IntelliJ;PyCharm;Vim,Linux-based,Linux-based;Windows,Git,Command-line;Version control hosting service w...,NaN,NaN,Confluence,Confluence,Microsoft Teams;Rocketchat,Rocketchat,Unsure,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not at all",18-24 years old,Man,"Or, in your own words:",Prefer to self-describe:,"Or, in your own words:","Or, in your own words:","Or, in your own words:",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN
70598,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,20,19,"Developer, front-end;Developer, full-stack;Dev...","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Other (please specify):,United States of America,ZMW Zambian kwacha,1.000000e+22,Yearly,Bash/Shell;HTML/CSS;JavaScript;Perl;PHP;SQL,NaN,MariaDB;MySQL,NaN,NaN,NaN,jQuery,NaN,NaN,NaN,NaN,NaN,Nano,NaN,BSD;Linux-based,Linux-based,Git;SVN,Command-line,NaN,NaN,NaN,NaN,NaN,NaN,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17568,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Freel...,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Online ...,NaN,10,6,"Developer, front-end;Developer, full-stack;Dev...",10 to 19 employees,I have some influence,Visit developer communities like Stack Overflo...,Italy,EUR European Euro,1.000000e+15,Monthly,HTML/CSS;JavaScript;PHP;SQL,C#;Go;HTML/CSS;Java;JavaScript;PHP;Python;R;SQ...,MariaDB;MongoDB;MySQL;SQLite,MariaDB;MongoDB;MySQL;SQLite,AWS;DigitalOcean;Managed Hosting,AWS;DigitalOcean;Google Cloud;Managed Hosting;...,Angular.js;jQuery;Laravel;Node.js;Vue.js,Angular;Angular.js;jQuery;Laravel;Node.js;Reac...,NaN,NaN,Docker;Homebrew;npm,Docker;Homebrew;npm,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,macOS,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,Trello,NaN,Google Chat;Microsoft Teams;Slack;Zoom,Google Chat;Microsoft Teams;Slack;Zoom,Indifferent,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,A few times per week,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,Yes,Independent contributor,8.0,Strongly agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Agree,Never,Never,Never,15-30 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN
19245,"I am not primarily a developer, but I write co...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Programming Games;Writ...,NaN,15,10,"Developer, front-end;Engineer, data;Developer,...",10 to 19 employees,I have little or no influence,Other (please specify):;Visit developer commun...,Kyrgyzstan,KGS\tKyrgyzstani som,5.000000e+12,Yearly,Bash/Shell;C++;Go;HTML/CSS;JavaScript;MATLAB;P...,Bash/Shell;HTML/CSS;JavaScript;PHP;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Oracle;Pos...,Elasticsearch;MariaDB;MySQL,DigitalOcean;Firebase;Google Cloud;Oracle Clou...,DigitalOcean;Firebase,Angular;Django;Drupal;Gatsby;jQuery;Laravel;No...,Angular;Vue.js,Apache Kafka;Apache Spark;React Native;Torch/P...,NaN,Docker,Ansible;Docker;Flow;Kubernetes;npm;Puppet;Unit...,Android Studio;Atom;IntelliJ;NetBeans;Neovim;N...,Atom;Notepad++;PhpStorm;PyCharm,Linux-based,BSD;Linux-based;Windows;Windows Subsystem for ...,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Planner;Trello,NaN,Google Chat;Rocketchat;Slack;Symphony;Zoom,NaN,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",35-44 years old,"Man;Or, in your own words:","Or, in your own words:",Straight / Heterosexual;Prefer to self-describe:,White;Asian;Multiracial;Central Asian,"Or, in your own words:;I am deaf / hard of hea...","Or, in your own words:",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
24641,I am a developer by profession,"Employed, full-time",Full in-person,Hobby;Contribute to open-source projects;Boots...,"Secondary school (e.g. American high school, G...",Books / Physical media,NaN,NaN,2,NaN,Project manager,"Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Read ratings or reviews on third party sites l...,Nigeria,NGN\tNigerian naira,1.500070e+12,Weekly,HTML/CSS;JavaScript;PowerShell;TypeScript,NaN,Cloud Firestore;Microsoft SQL Server;Firebase ...,NaN,DigitalOcean;Google Cloud;Microsoft Azure;Open...,DigitalOcean;Google Cloud;Microsoft Azure;Open...,ASP.NET;Express,NaN,.NET;Flutter,NaN,Flow;Terraform,NaN,Eclipse;NetBeans;Notepad++;Qt Creator,NaN,NaN,Windows,I don't use one,NaN,NaN,NaN,Adobe Workfront;Microsoft Planner;Microsoft Lists,Stack Overflow for Teams,NaN,NaN,Unfavorable,Stack Overflow for Teams (private knowledge sh...,A few times per week,No,NaN,Neutral,18-24 years old,Man,No,Straight / Heterosexual;Queer,African;South American,None of the above,None of the above,Yes,Independent contributor,9.0,Disagree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,NaN,NaN,Over 120 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
31191,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Other doctoral degree (Ph.D., Ed.D., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Codecademy;Pluralsight;edX;Udac...,10,Less than 1 year,Data scientist or machine learning specialist;...,I don’t know,I have a great deal of influence,Other (please specify):;Start a free trial;Vis...,United States of America,USD\tUnited States dollar,1.000000e+12,Monthly,APL;Assembly;Bash/Shell;C;C#;C++;Clojure;COBOL...,APL;Assembly;Bash/Shell;C;C#;C++;Clojure;COBOL...,Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...,Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...,AWS;Colocation;DigitalOcean;Firebase;Google Cl...,AWS;Colocation;DigitalOcean;Firebase;Google Cl...,Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...,Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...,.NET;Apache Kafka;Apache Spark;Capacitor;Cordo...,.NET;Apache Kafka;Apache Spark;Capacitor;Cordo...,Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...,Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...,Atom;CLion;Eclipse;Emacs;GoLand;IntelliJ;IPyth...,Atom;CLion;Eclipse;Emacs;GoLand;IntelliJ;IPyth...,BSD;Linux-based;macOS;Windows;Windows Subsyste...,BSD;Linux-based;macOS;Windows;Windows Subsyste...,I don't use one,NaN,NaN,NaN,Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...,Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...,Cisco Webex Teams;Coolfire Core;Google Chat;Ma...,Cisco Webex Teams;Coolfire Core;Google Chat;Ma...,Very favorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,NaN,25-34 years old,"Or, in your own words:",No,Straight / Heterosexual,White;Indian;European;North American;Middle Ea...,Prefer not to say,I have a concentration and/or memory disorder ...,Yes,People manager,15.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,60-120 minutes a day,Very short,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
71604,I am a developer by profession,"Employed, part-time",Fully remote,Hobby,Something else,Other (please specify):,NaN,NaN,4,NaN,Scientist,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,Start a free trial,"Iran, Islamic Republic of...",USD\tUnited States dollar,9.363220e+09,Monthly,APL,NaN,Cassandra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,NaN,NaN,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams,Google Chat;Microsoft Teams;Wickr,Unsure,Stack Exchange,Less than once per month or monthly,No,NaN,Neutral,35-44 years old,Prefer not to say,No,NaN,Asian,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
34412,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Bootstrapping a business;Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;V...,Udemy;Pluralsight;Udacity,16,12,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,"Iran, Islamic Republic of...",IRR\tIranian rial,7.200000e+09,Monthly,C;C#;JavaScript;PHP;SQL;TypeScript,C#;Dart;F#;Go;JavaScript;SQL;TypeScript,Microsoft SQL Server;MySQL;Oracle,Cassandra;Elasticsearch;Microsoft SQL Server;P...,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core ;jQuer...,Angular;ASP.NET Core ;Node.js;Vue.js,.NET;Cordova;Ionic;React Native;Xamarin,.NET;Capacitor;Flutter;Ionic,npm;Yarn,Docker;Kubernetes;npm;Yarn,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Microsoft Teams,Microsoft Teams;Zoom,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Yes,People manager,16.0,Agree,Neither agree nor disagree,Agree,Agree,NaN,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Appropriate in length,Easy,2042400.0
49875,I am a developer by profession,"Employed, full-time",Fully remote,Contribute to open-source projects,Primary/elementary school,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Codecademy;Pluralsight;edX;Udac...,19,10,Data scientist or machine learning specialist;...,"1,000 to 4,999 employees",I have little or no influence,Other (please specify):;Start a free trial;Vis...,Angola,INR\tIndian rupee,6.438169e+09,Monthly,APL;Assembly;Bash/Shell;C#;C++;Clojure;COBOL;C...,APL;Assembly;Bash/Shell;C#;C++;Clojure;COBOL;C...,Cassandra;Couchbase;Cloud Firestore;DynamoDB;E...,Cassandra;Couchbase;Cloud Firestore;DynamoDB;E...,AWS;Colocation;Microsoft Azure;Oracle Cloud In...,AWS;Colocation;Microsoft Azure;Oracle Cloud In...,Angular;ASP.NET;ASP.NET Core ;Ruby on Rails;Sv...,Angular;ASP.NET Core ;Ruby on Rails;Svelte;Sym...,.NET;Capacitor;Electron;Flutter;GTK;Hadoop;Ion...,.NET;Capacitor;Electron;Flutter;GTK;Hadoop;Ion...,Ansible;Unreal Engine;Yarn,Ansible;Unreal Engine;Yarn,Android Studio;Vim;Xcode,Android Studio;Vim;Xcode,BSD;Windows Subsystem for Linux (WSL),BSD;Windows Subsystem for Linux (WSL),Git;Mercurial;SVN,Code editor;Command-line;Version control hosti...,NaN,NaN,Airtable;Asana;Cerri;ClickUp;Confluence;DingTa...,Airtable;Asana;Cerri;ClickUp;Confluence;DingTa...,Cisco Webex Teams;Zoom,Cisco Webex Teams;Zoom,Indifferent,I have never visited Stack Overflow or the Sta...,NaN,Yes,A few times per month or weekly,"Yes, somewhat",45-54 years old,"Man;Woman;Non-binary, genderqueer, or gender n...",Yes,Bisexual;Straight / Heterosexual;Gay or Lesbia...,White;Indian;European;North American;Middle Ea...,I am deaf / hard of hearing;I am blind / have ...,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,45.0,Strongly disagree,Strongly disagree,Strongly disagree,Disagree,Agree,Neither agree nor disagree,Agree,Never,1-2 times a week,6-10 times a week,30-60 minutes a day,30-60 minutes a day,Somewhat short,Innersource initiative;DevOps function;Microse...,Yes,NaN,NaN,Appropriate in length,Difficult,NaN

# Tutorial#8

In [3]:
df['CompTotal'].median()    # Middle value of sorted array

77500.0

In [4]:
df['CompTotal'].mean()  # Mean is biased towards the highest or the lowest value in dataset

2.342434022174796e+52

In [10]:
df['Ethnicity'].count() #number of non-NA rows

69474

In [16]:
cg = df.groupby('Country')

In [25]:
cg.get_group('Pakistan')['Ethnicity']

916                    Asian
1198             South Asian
1390         Southeast Asian
2917     Asian;Central Asian
3044         Southeast Asian
                ...
72824            South Asian
72868            South Asian
72908      Asian;South Asian
72937      Asian;South Asian
73028            South Asian
Name: Ethnicity, Length: 711, dtype: object

In [30]:
cg['Sexuality'].value_counts(normalize=True).loc['Pakistan']

Sexuality
Straight / Heterosexual                            0.768274
Prefer not to say                                  0.149300
Bisexual                                           0.035770
Prefer to self-describe:                           0.029549
Gay or Lesbian                                     0.004666
Queer                                              0.004666
Bisexual;Gay or Lesbian                            0.001555
Bisexual;Prefer to self-describe:                  0.001555
Bisexual;Queer                                     0.001555
Bisexual;Straight / Heterosexual                   0.001555
Bisexual;Straight / Heterosexual;Gay or Lesbian    0.001555
Name: proportion, dtype: float64

In [35]:
cg['CompTotal'].median().loc['Pakistan']

100000.0

In [36]:
cg['CompTotal'].median()

Country
Afghanistan                                                  6000.0
Albania                                                      5500.0
Algeria                                                     75000.0
Andorra                                                     31500.0
Angola                                                     600000.0
Antigua and Barbuda                                             NaN
Argentina                                                  110000.0
Armenia                                                    632500.0
Australia                                                  125000.0
Austria                                                     49750.0
Azerbaijan                                                   3500.0
Bahamas                                                         NaN
Bahrain                                                      2865.0
Bangladesh                                                  60000.0
Barbados                                                   100000.0
Belarus                                                      3600.0
Belgium                                                      4600.0
Belize                                                          NaN
Benin                                                     1000000.0
Bhutan                                                     330000.0
Bolivia                                                      7000.0
Bosnia and Herzegovina                                       4500.0
Botswana                                                     9000.0
Brazil                                                      11000.0
Brunei Darussalam                                               NaN
Bulgaria                                                     6000.0
Burkina Faso                                                    NaN
Cambodia                                                     1400.0
Cameroon                                                   200000.0
Canada                                                     112000.0
Cape Verde                                                  90000.0
Chad                                                            NaN
Chile                                                     1800000.0
China                                                       32500.0
Colombia                                                  5575000.0
Congo, Republic of the...                                    6500.0
Costa Rica                                                  75000.0
Croatia                                                     20043.0
Cuba                                                         1500.0
Cyprus                                                      12000.0
Czech Republic                                              82177.0
Côte d'Ivoire                                              425000.0
Democratic Republic of the Congo                             2500.0
Denmark                                                     55000.0
Djibouti                                                        NaN
Dominican Republic                                          56000.0
Ecuador                                                      2300.0
Egypt                                                       12000.0
El Salvador                                                  2400.0
Estonia                                                      4800.0
Ethiopia                                                    16500.0
Fiji                                                        50000.0
Finland                                                      5500.0
France                                                      44000.0
Gabon                                                           NaN
Gambia                                                          NaN
Georgia                                                      6000.0
Germany                                                     59000.0
Ghana                                                        6000.0
Greece                                                      18000.0
Guatemala                                                   30000.0
Guinea                                                    8500000.0
Guyana                                                    1006000.0
Haiti                                                    14566666.0
Honduras                                                    16000.0
Hong Kong (S.A.R.)                                          40000.0
Hungary                                                    850000.0
Iceland                                                   1000000.0
India                                                      885000.0
Indonesia                                                10000000.0
Iran, Islamic Republic of...                            115000000.0
Iraq                                                        60000.0
Ireland                                                     83200.0
Isle of Man                                                 43000.0
Israel                                                      37000.0
Italy                                                       35000.0
Jamaica                                                   2000000.0
Japan                                                     5500000.0
Jordan                                                       2000.0
Kazakhstan                                                 450000.0
Kenya                                                       97000.0
Kosovo                                                       2000.0
Kuwait                                                       1775.0
Kyrgyzstan                                                 100000.0
Lao People's Democratic Republic                           225000.0
Latvia                                                       3900.0
Lebanon                                                      1900.0
Lesotho                                                         NaN
Liberia                                                         NaN
Libyan Arab Jamahiriya                                       5750.0
Lithuania                                                    4478.0
Luxembourg                                                  62500.0
Madagascar                                                1700000.0
Malawi                                                     325000.0
Malaysia                                                     6000.0
Maldives                                                    24500.0
Mali                                                        50000.0
Malta                                                       48650.0
Mauritania                                                      NaN
Mauritius                                                   61000.0
Mexico                                                      42000.0
Monaco                                                     100000.0
Mongolia                                                  1750000.0
Montenegro                                                   2269.0
Morocco                                                     12000.0
Mozambique                                                  25000.0
Myanmar                                                    450000.0
Namibia                                                         NaN
Nepal                                                       50000.0
Netherlands                                                 50000.0
New Zealand                                                120000.0
Nicaragua                                                    1800.0
Niger                                                           NaN
Nigeria                                                    300000.0
Nomadic                                                     61500.0
North Korea                                                     NaN
Norway                                                     750000.0
Oman                                                         1000.0
Pakistan                                                   100000.0
Palau                                                      135000.0
Palestine                                                    2250.0
Panama                                                       3000.0
Papua New Guinea                                                NaN
Paraguay                                                  3000000.0
Peru                                                         6000.0
Philippines                                                 61500.0
Poland                                                      16000.0
Portugal                                                    26000.0
Qatar                                                       12345.0
Republic of Korea                                        32500000.0
Republic of Moldova                                         12000.0
Romania                                                     15200.0
Russian Federation                                         170000.0
Rwanda                                                     700000.0
Saint Kitts and Nevis                                           NaN
Saint Lucia                                                  2000.0
San Marino                                                      NaN
Saudi Arabia                                                20000.0
Senegal                                                   3000000.0
Serbia                                                      60000.0
Seychelles                                                   2700.0
Sierra Leone                                                    NaN
Singapore                                                   11000.0
Slovakia                                                     3300.0
Slovenia                                                     4216.5
Solomon Islands                                                 0.0
Somalia                                                     12000.0
South Africa                                                80000.0
South Korea                                              40000000.0
Spain                                                       40000.0
Sri Lanka                                                  180000.0
Sudan                                                      180000.0
Suriname                                                      800.0
Swaziland                                                       0.0
Sweden                                                      52000.0
Switzerland                                                102000.0
Syrian Arab Republic                                         1550.0
Taiwan                                                     700000.0
Tajikistan                                                   3500.0
Thailand                                                    85000.0
The former Yugoslav Republic of Macedonia                   66000.0
Timor-Leste                                                  4950.0
Togo                                                       175000.0
Trinidad and Tobago                                         13800.0
Tunisia                                                      2200.0
Turkey                                                      18000.0
Turkmenistan                                                10000.0
Uganda                                                    1300000.0
Ukraine                                                      7250.0
United Arab Emirates                                        20000.0
United Kingdom of Great Britain and Northern Ireland        58000.0
United Republic of Tanzania                                500000.0
United States of America                                   140000.0
Uruguay                                                     64000.0
Uzbekistan                                                   4250.0
Venezuela, Bolivarian Republic of...                         1094.0
Viet Nam                                                 15000000.0
Yemen                                                       20750.0
Zambia                                                       6200.0
Zimbabwe                                                      950.0
Name: CompTotal, dtype: float64

In [39]:
cg['CompTotal'].agg(['median','mean'])      #apply multiple aggregate functions

                                                         median          mean
Country
Afghanistan                                              6000.0  3.808414e+06
Albania                                                  5500.0  5.104657e+05
Algeria                                                 75000.0  8.754444e+04
Andorra                                                 31500.0  7.677250e+04
Angola                                                 600000.0  1.287990e+09
Antigua and Barbuda                                         NaN           NaN
Argentina                                              110000.0  3.983275e+05
Armenia                                                632500.0  1.387942e+06
Australia                                              125000.0  3.719887e+05
Austria                                                 49750.0  4.824716e+04
Azerbaijan                                               3500.0  7.081739e+03
Bahamas                                                     NaN           NaN
Bahrain                                                  2865.0  6.982500e+03
Bangladesh                                              60000.0  1.945499e+05
Barbados                                               100000.0  1.183667e+05
Belarus                                                  3600.0  5.393791e+03
Belgium                                                  4600.0  2.972684e+04
Belize                                                      NaN           NaN
Benin                                                 1000000.0  2.034882e+06
Bhutan                                                 330000.0  3.600000e+05
Bolivia                                                  7000.0  1.362381e+04
Bosnia and Herzegovina                                   4500.0  1.389462e+04
Botswana                                                 9000.0  2.768750e+04
Brazil                                                  11000.0  6.205287e+04
Brunei Darussalam                                           NaN           NaN
Bulgaria                                                 6000.0  2.705227e+04
Burkina Faso                                                NaN           NaN
Cambodia                                                 1400.0  1.029014e+07
Cameroon                                               200000.0  2.202650e+05
Canada                                                 112000.0  1.259291e+05
Cape Verde                                              90000.0  9.000000e+04
Chad                                                        NaN           NaN
Chile                                                 1800000.0  3.370773e+06
China                                                   32500.0  2.667926e+05
Colombia                                              5575000.0  1.588645e+07
Congo, Republic of the...                                6500.0  2.028333e+05
Costa Rica                                              75000.0  1.897556e+06
Croatia                                                 20043.0  7.396485e+04
Cuba                                                     1500.0  1.443781e+04
Cyprus                                                  12000.0  4.780000e+04
Czech Republic                                          82177.0  3.057750e+06
Côte d'Ivoire                                          425000.0  5.879000e+05
Democratic Republic of the Congo                         2500.0  3.833333e+03
Denmark                                                 55000.0  1.581683e+05
Djibouti                                                    NaN           NaN
Dominican Republic                                      56000.0  3.323069e+05
Ecuador                                                  2300.0  1.875000e+55
Egypt                                                   12000.0  1.036615e+06
El Salvador                                              2400.0  1.090000e+04
Estonia                                                  4800.0  2.233822e+04
Ethiopia                                                16500.0  1.096842e+05
Fiji                                                    50000.0  5.000000e+04
Finland                                                  5500.0  2.533198e+04
France                                                  44000.0  5.022446e+04
Gabon                                                       NaN           NaN
Gambia                                                      NaN           NaN
Georgia                                                  6000.0  2.414344e+04
Germany                                                 59000.0  5.487846e+04
Ghana                                                    6000.0  1.816504e+04
Greece                                                  18000.0  2.528644e+04
Guatemala                                               30000.0  6.752069e+04
Guinea                                                8500000.0  1.550000e+07
Guyana                                                1006000.0  9.555000e+05
Haiti                                                14566666.0  1.456667e+07
Honduras                                                16000.0  5.484615e+04
Hong Kong (S.A.R.)                                      40000.0  2.068975e+05
Hungary                                                850000.0  2.569694e+06
Iceland                                               1000000.0  3.458500e+06
India                                                  885000.0  1.693451e+06
Indonesia                                            10000000.0  5.137083e+07
Iran, Islamic Republic of...                        115000000.0  2.411151e+08
Iraq                                                    60000.0  9.691853e+05
Ireland                                                 83200.0  8.394585e+04
Isle of Man                                             43000.0  4.990000e+04
Israel                                                  37000.0  1.012145e+05
Italy                                                   35000.0  1.223990e+12
Jamaica                                               2000000.0  2.091316e+06
Japan                                                 5500000.0  7.109150e+06
Jordan                                                   2000.0  9.015120e+03
Kazakhstan                                             450000.0  3.386929e+06
Kenya                                                   97000.0  3.790892e+05
Kosovo                                                   2000.0  1.191455e+04
Kuwait                                                   1775.0  1.566667e+03
Kyrgyzstan                                             100000.0  4.545455e+11
Lao People's Democratic Republic                       225000.0  2.616667e+05
Latvia                                                   3900.0  1.971547e+04
Lebanon                                                  1900.0  2.898800e+04
Lesotho                                                     NaN           NaN
Liberia                                                     NaN           NaN
Libyan Arab Jamahiriya                                   5750.0  7.690000e+03
Lithuania                                                4478.0  1.994008e+04
Luxembourg                                              62500.0  5.475000e+04
Madagascar                                            1700000.0  2.243157e+06
Malawi                                                 325000.0  3.427500e+05
Malaysia                                                 6000.0  3.378176e+04
Maldives                                                24500.0  5.818750e+04
Mali                                                    50000.0  8.837167e+05
Malta                                                   48650.0  5.385909e+04
Mauritania                                                  NaN           NaN
Mauritius                                               61000.0  5.379462e+05
Mexico                                                  42000.0  1.359111e+05
Monaco                                                 100000.0  1.000000e+05
Mongolia                                              1750000.0  2.200215e+06
Montenegro                                               2269.0  2.562333e+03
Morocco                                                 12000.0  2.407570e+04
Mozambique                                              25000.0  4.325000e+04
Myanmar                                                450000.0  9.884011e+05
Namibia                                                     NaN           NaN
Nepal                                                   50000.0  1.980378e+05
Netherlands                                             50000.0  5.087067e+04
New Zealand                                            120000.0  1.738483e+05
Nicaragua                                                1800.0  1.563636e+04
Niger                                                       NaN           NaN
Nigeria                                                300000.0  1.136584e+10
Nomadic                                                 61500.0  7.382500e+04
North Korea                                                 NaN           NaN
Norway                                                 750000.0  8.392448e+05
Oman                                                     1000.0  1.125000e+03
Pakistan                                               100000.0  3.439601e+05
Palau                                                  135000.0  1.350000e+05
Palestine                                                2250.0  3.950929e+03
Panama                                                   3000.0  2.381526e+04
Papua New Guinea                                            NaN           NaN
Paraguay                                              3000000.0  1.975151e+07
Peru                                                     6000.0  2.260945e+04
Philippines                                             61500.0  2.375922e+05
Poland                                                  16000.0  5.337473e+04
Portugal                                                26000.0  1.566452e+05
Qatar                                                   12345.0  1.557314e+04
Republic of Korea                                    32500000.0  3.461585e+07
Republic of Moldova                                     12000.0  6.986243e+04
Romania                                                 15200.0  3.901268e+04
Russian Federation                                     170000.0  3.854137e+05
Rwanda                                                 700000.0  3.764343e+06
Saint Kitts and Nevis                                       NaN           NaN
Saint Lucia                                              2000.0  2.000000e+03
San Marino                                                  NaN           NaN
Saudi Arabia                                            20000.0  1.066029e+06
Senegal                                               3000000.0  5.126143e+06
Serbia                                                  60000.0  1.799524e+05
Seychelles                                               2700.0  2.700000e+03
Sierra Leone                                                NaN           NaN
Singapore                                               11000.0  7.219033e+04
Slovakia                                                 3300.0  1.435218e+04
Slovenia                                                 4216.5  2.220290e+04
Solomon Islands                                             0.0  0.000000e+00
Somalia                                                 12000.0  1.200000e+04
South Africa                                            80000.0  3.115172e+05
South Korea                                          40000000.0  5.140019e+07
Spain                                                   40000.0  4.416284e+04
Sri Lanka                                              180000.0  6.915069e+06
Sudan                                                  180000.0  1.730955e+05
Suriname                                                  800.0  8.000000e+02
Swaziland                                                   0.0  0.000000e+00
Sweden                                                  52000.0  1.704226e+05
Switzerland                                            102000.0  9.991170e+04
Syrian Arab Republic                                     1550.0  2.286907e+05
Taiwan                                                 700000.0  1.055883e+07
Tajikistan                                               3500.0  3.950000e+03
Thailand                                                85000.0  1.227580e+07
The former Yugoslav Republic of Macedonia               66000.0  1.791259e+05
Timor-Leste                                              4950.0  4.950000e+03
Togo                                                   175000.0  1.750000e+05
Trinidad and Tobago                                     13800.0  1.615000e+04
Tunisia                                                  2200.0  4.710786e+03
Turkey                                                  18000.0  4.588648e+04
Turkmenistan                                            10000.0  1.830000e+04
Uganda                                                1300000.0  2.420922e+06
Ukraine                                                  7250.0  4.756761e+04
United Arab Emirates                                    20000.0  6.020203e+04
United Kingdom of Great Britain and Northern Ir...      58000.0  6.748744e+04
United Republic of Tanzania                            500000.0  1.255664e+07
United States of America                               140000.0  1.138952e+48
Uruguay                                                 64000.0  1.579212e+05
Uzbekistan                                               4250.0  3.454374e+06
Venezuela, Bolivarian Republic of...                     1094.0  4.498590e+03
Viet Nam                                             15000000.0  4.443807e+07
Yemen                                                   20750.0  1.071667e+05
Zambia                                                   6200.0  5.613333e+03
Zimbabwe                                                  950.0  9.445000e+04

In [72]:
cg['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').mean())

Country
Afghanistan                                             0.390625
Albania                                                 0.339286
Algeria                                                 0.527778
Andorra                                                 0.266667
Angola                                                  0.272727
Antigua and Barbuda                                     0.000000
Argentina                                               0.352250
Armenia                                                 0.483516
Australia                                               0.486207
Austria                                                 0.462740
Azerbaijan                                              0.492754
Bahamas                                                 0.250000
Bahrain                                                 0.428571
Bangladesh                                              0.420000
Barbados                                                0.500000
Belarus                                                 0.416667
Belgium                                                 0.498387
Belize                                                  0.666667
Benin                                                   0.636364
Bhutan                                                  0.400000
Bolivia                                                 0.431818
Bosnia and Herzegovina                                  0.346535
Botswana                                                0.666667
Brazil                                                  0.419913
Brunei Darussalam                                       1.000000
Bulgaria                                                0.349030
Burkina Faso                                            1.000000
Cambodia                                                0.382353
Cameroon                                                0.500000
Canada                                                  0.516863
Cape Verde                                              0.250000
Chad                                                    0.333333
Chile                                                   0.492537
China                                                   0.540717
Colombia                                                0.477745
Congo, Republic of the...                               0.181818
Costa Rica                                              0.500000
Croatia                                                 0.375000
Cuba                                                    0.548387
Cyprus                                                  0.483333
Czech Republic                                          0.472384
Côte d'Ivoire                                           0.571429
Democratic Republic of the Congo                        0.714286
Denmark                                                 0.414679
Djibouti                                                0.000000
Dominican Republic                                      0.301205
Ecuador                                                 0.421687
Egypt                                                   0.394805
El Salvador                                             0.311111
Estonia                                                 0.450000
Ethiopia                                                0.424658
Fiji                                                    1.000000
Finland                                                 0.555556
France                                                  0.520311
Gabon                                                   0.000000
Gambia                                                  0.500000
Georgia                                                 0.485714
Germany                                                 0.497674
Ghana                                                   0.500000
Greece                                                  0.483577
Guatemala                                               0.555556
Guinea                                                  0.600000
Guyana                                                  0.500000
Haiti                                                   0.666667
Honduras                                                0.392857
Hong Kong (S.A.R.)                                      0.542373
Hungary                                                 0.434125
Iceland                                                 0.392857
India                                                   0.474511
Indonesia                                               0.436538
Iran, Islamic Republic of...                            0.433989
Iraq                                                    0.450980
Ireland                                                 0.525680
Isle of Man                                             0.583333
Israel                                                  0.573418
Italy                                                   0.465690
Jamaica                                                 0.523810
Japan                                                   0.501520
Jordan                                                  0.281250
Kazakhstan                                              0.463768
Kenya                                                   0.492424
Kosovo                                                  0.379310
Kuwait                                                  0.700000
Kyrgyzstan                                              0.318182
Lao People's Democratic Republic                        0.857143
Latvia                                                  0.431579
Lebanon                                                 0.449275
Lesotho                                                 0.500000
Liberia                                                 0.500000
Libyan Arab Jamahiriya                                  0.500000
Lithuania                                               0.297170
Luxembourg                                              0.446429
Madagascar                                              0.416667
Malawi                                                  0.428571
Malaysia                                                0.457286
Maldives                                                0.250000
Mali                                                    0.700000
Malta                                                   0.512821
Mauritania                                              0.500000
Mauritius                                               0.428571
Mexico                                                  0.438503
Monaco                                                  0.000000
Mongolia                                                0.444444
Montenegro                                              0.315789
Morocco                                                 0.427928
Mozambique                                              0.363636
Myanmar                                                 0.320000
Namibia                                                 0.250000
Nepal                                                   0.511521
Netherlands                                             0.461538
New Zealand                                             0.429885
Nicaragua                                               0.333333
Niger                                                   0.333333
Nigeria                                                 0.436000
Nomadic                                                 0.500000
North Korea                                             1.000000
Norway                                                  0.469474
Oman                                                    0.692308
Pakistan                                                0.397163
Palau                                                   0.500000
Palestine                                               0.441176
Panama                                                  0.464286
Papua New Guinea                                        1.000000
Paraguay                                                0.365854
Peru                                                    0.451128
Philippines                                             0.446023
Poland                                                  0.470383
Portugal                                                0.474820
Qatar                                                   0.600000
Republic of Korea                                       0.537313
Republic of Moldova                                     0.162162
Romania                                                 0.380623
Russian Federation                                      0.485597
Rwanda                                                  0.650000
Saint Kitts and Nevis                                   1.000000
Saint Lucia                                             0.333333
San Marino                                              0.000000
Saudi Arabia                                            0.482143
Senegal                                                 0.384615
Serbia                                                  0.355872
Seychelles                                              0.000000
Sierra Leone                                            0.000000
Singapore                                               0.657778
Slovakia                                                0.497797
Slovenia                                                0.487633
Solomon Islands                                         1.000000
Somalia                                                 0.181818
South Africa                                            0.412371
South Korea                                             0.527027
Spain                                                   0.462865
Sri Lanka                                               0.530822
Sudan                                                   0.258065
Suriname                                                0.750000
Swaziland                                               0.571429
Sweden                                                  0.459113
Switzerland                                             0.546926
Syrian Arab Republic                                    0.342857
Taiwan                                                  0.584071
Tajikistan                                              0.272727
Thailand                                                0.454023
The former Yugoslav Republic of Macedonia               0.220000
Timor-Leste                                             1.000000
Togo                                                    0.333333
Trinidad and Tobago                                     0.454545
Tunisia                                                 0.474747
Turkey                                                  0.454995
Turkmenistan                                            0.533333
Uganda                                                  0.451613
Ukraine                                                 0.382253
United Arab Emirates                                    0.424242
United Kingdom of Great Britain and Northern Ireland    0.499880
United Republic of Tanzania                             0.500000
United States of America                                0.521788
Uruguay                                                 0.405660
Uzbekistan                                              0.421687
Venezuela, Bolivarian Republic of...                    0.440678
Viet Nam                                                0.447368
Yemen                                                   0.285714
Zambia                                                  0.352941
Zimbabwe                                                0.392857
Name: LanguageHaveWorkedWith, dtype: float64